// Code generated by ent, DO NOT EDIT.

package managedproxylease

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the managedproxylease type in the database.
	Label = "managed_proxy_lease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldProviderConfigID holds the string denoting the provider_config_id field in the database.
	FieldProviderConfigID = "provider_config_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldTargetCountry holds the string denoting the target_country field in the database.
	FieldTargetCountry = "target_country"
	// FieldTargetState holds the string denoting the target_state field in the database.
	FieldTargetState = "target_state"
	// FieldTargetCity holds the string denoting the target_city field in the database.
	FieldTargetCity = "target_city"
	// FieldStrict holds the string denoting the strict field in the database.
	FieldStrict = "strict"
	// FieldLifetimeMinutes holds the string denoting the lifetime_minutes field in the database.
	FieldLifetimeMinutes = "lifetime_minutes"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldHealthStatus holds the string denoting the health_status field in the database.
	FieldHealthStatus = "health_status"
	// FieldHealthCheckedAt holds the string denoting the health_checked_at field in the database.
	FieldHealthCheckedAt = "health_checked_at"
	// FieldObservedExitIP holds the string denoting the observed_exit_ip field in the database.
	FieldObservedExitIP = "observed_exit_ip"
	// FieldObservedCountry holds the string denoting the observed_country field in the database.
	FieldObservedCountry = "observed_country"
	// FieldObservedState holds the string denoting the observed_state field in the database.
	FieldObservedState = "observed_state"
	// FieldObservedCity holds the string denoting the observed_city field in the database.
	FieldObservedCity = "observed_city"
	// FieldObservedLatencyMs holds the string denoting the observed_latency_ms field in the database.
	FieldObservedLatencyMs = "observed_latency_ms"
	// FieldActivatedAt holds the string denoting the activated_at field in the database.
	FieldActivatedAt = "activated_at"
	// FieldLastRotatedAt holds the string denoting the last_rotated_at field in the database.
	FieldLastRotatedAt = "last_rotated_at"
	// FieldNextRotationAt holds the string denoting the next_rotation_at field in the database.
	FieldNextRotationAt = "next_rotation_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldFailureCount holds the string denoting the failure_count field in the database.
	FieldFailureCount = "failure_count"
	// FieldConsecutiveFailureCount holds the string denoting the consecutive_failure_count field in the database.
	FieldConsecutiveFailureCount = "consecutive_failure_count"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastErrorAt holds the string denoting the last_error_at field in the database.
	FieldLastErrorAt = "last_error_at"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeProxy holds the string denoting the proxy edge name in mutations.
	EdgeProxy = "proxy"
	// EdgeProviderConfig holds the string denoting the provider_config edge name in mutations.
	EdgeProviderConfig = "provider_config"
	// Table holds the table name of the managedproxylease in the database.
	Table = "managed_proxy_leases"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "managed_proxy_leases"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// ProxyTable is the table that holds the proxy relation/edge.
	ProxyTable = "managed_proxy_leases"
	// ProxyInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	ProxyInverseTable = "proxies"
	// ProxyColumn is the table column denoting the proxy relation/edge.
	ProxyColumn = "proxy_id"
	// ProviderConfigTable is the table that holds the provider_config relation/edge.
	ProviderConfigTable = "managed_proxy_leases"
	// ProviderConfigInverseTable is the table name for the CatProxyProviderConfig entity.
	// It exists in this package in order to avoid circular dependency with the "catproxyproviderconfig" package.
	ProviderConfigInverseTable = "catproxy_provider_configs"
	// ProviderConfigColumn is the table column denoting the provider_config relation/edge.
	ProviderConfigColumn = "provider_config_id"
)

// Columns holds all SQL columns for managedproxylease fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldProxyID,
	FieldProviderConfigID,
	FieldSessionID,
	FieldTargetCountry,
	FieldTargetState,
	FieldTargetCity,
	FieldStrict,
	FieldLifetimeMinutes,
	FieldState,
	FieldHealthStatus,
	FieldHealthCheckedAt,
	FieldObservedExitIP,
	FieldObservedCountry,
	FieldObservedState,
	FieldObservedCity,
	FieldObservedLatencyMs,
	FieldActivatedAt,
	FieldLastRotatedAt,
	FieldNextRotationAt,
	FieldExpiresAt,
	FieldFailureCount,
	FieldConsecutiveFailureCount,
	FieldLastError,
	FieldLastErrorAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// TargetCountryValidator is a validator for the "target_country" field. It is called by the builders before save.
	TargetCountryValidator func(string) error
	// TargetStateValidator is a validator for the "target_state" field. It is called by the builders before save.
	TargetStateValidator func(string) error
	// TargetCityValidator is a validator for the "target_city" field. It is called by the builders before save.
	TargetCityValidator func(string) error
	// LifetimeMinutesValidator is a validator for the "lifetime_minutes" field. It is called by the builders before save.
	LifetimeMinutesValidator func(int) error
	// ObservedExitIPValidator is a validator for the "observed_exit_ip" field. It is called by the builders before save.
	ObservedExitIPValidator func(string) error
	// ObservedCountryValidator is a validator for the "observed_country" field. It is called by the builders before save.
	ObservedCountryValidator func(string) error
	// ObservedStateValidator is a validator for the "observed_state" field. It is called by the builders before save.
	ObservedStateValidator func(string) error
	// ObservedCityValidator is a validator for the "observed_city" field. It is called by the builders before save.
	ObservedCityValidator func(string) error
	// DefaultFailureCount holds the default value on creation for the "failure_count" field.
	DefaultFailureCount int
	// DefaultConsecutiveFailureCount holds the default value on creation for the "consecutive_failure_count" field.
	DefaultConsecutiveFailureCount int
)

// State defines the type for the "state" enum field.
type State string

// StatePending is the default value of the State enum.
const DefaultState = StatePending

// State values.
const (
	StatePending  State = "pending"
	StateActive   State = "active"
	StateRotating State = "rotating"
	StateExpired  State = "expired"
	StateFailed   State = "failed"
	StateReleased State = "released"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePending, StateActive, StateRotating, StateExpired, StateFailed, StateReleased:
		return nil
	default:
		return fmt.Errorf("managedproxylease: invalid enum value for state field: %q", s)
	}
}

// HealthStatus defines the type for the "health_status" enum field.
type HealthStatus string

// HealthStatusUnknown is the default value of the HealthStatus enum.
const DefaultHealthStatus = HealthStatusUnknown

// HealthStatus values.
const (
	HealthStatusUnknown   HealthStatus = "unknown"
	HealthStatusHealthy   HealthStatus = "healthy"
	HealthStatusDegraded  HealthStatus = "degraded"
	HealthStatusUnhealthy HealthStatus = "unhealthy"
)

func (hs HealthStatus) String() string {
	return string(hs)
}

// HealthStatusValidator is a validator for the "health_status" field enum values. It is called by the builders before save.
func HealthStatusValidator(hs HealthStatus) error {
	switch hs {
	case HealthStatusUnknown, HealthStatusHealthy, HealthStatusDegraded, HealthStatusUnhealthy:
		return nil
	default:
		return fmt.Errorf("managedproxylease: invalid enum value for health_status field: %q", hs)
	}
}

// OrderOption defines the ordering options for the ManagedProxyLease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByProviderConfigID orders the results by the provider_config_id field.
func ByProviderConfigID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderConfigID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByTargetCountry orders the results by the target_country field.
func ByTargetCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetCountry, opts...).ToFunc()
}

// ByTargetState orders the results by the target_state field.
func ByTargetState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetState, opts...).ToFunc()
}

// ByTargetCity orders the results by the target_city field.
func ByTargetCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetCity, opts...).ToFunc()
}

// ByStrict orders the results by the strict field.
func ByStrict(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrict, opts...).ToFunc()
}

// ByLifetimeMinutes orders the results by the lifetime_minutes field.
func ByLifetimeMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifetimeMinutes, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByHealthStatus orders the results by the health_status field.
func ByHealthStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthStatus, opts...).ToFunc()
}

// ByHealthCheckedAt orders the results by the health_checked_at field.
func ByHealthCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthCheckedAt, opts...).ToFunc()
}

// ByObservedExitIP orders the results by the observed_exit_ip field.
func ByObservedExitIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedExitIP, opts...).ToFunc()
}

// ByObservedCountry orders the results by the observed_country field.
func ByObservedCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedCountry, opts...).ToFunc()
}

// ByObservedState orders the results by the observed_state field.
func ByObservedState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedState, opts...).ToFunc()
}

// ByObservedCity orders the results by the observed_city field.
func ByObservedCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedCity, opts...).ToFunc()
}

// ByObservedLatencyMs orders the results by the observed_latency_ms field.
func ByObservedLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedLatencyMs, opts...).ToFunc()
}

// ByActivatedAt orders the results by the activated_at field.
func ByActivatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivatedAt, opts...).ToFunc()
}

// ByLastRotatedAt orders the results by the last_rotated_at field.
func ByLastRotatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRotatedAt, opts...).ToFunc()
}

// ByNextRotationAt orders the results by the next_rotation_at field.
func ByNextRotationAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRotationAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByFailureCount orders the results by the failure_count field.
func ByFailureCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCount, opts...).ToFunc()
}

// ByConsecutiveFailureCount orders the results by the consecutive_failure_count field.
func ByConsecutiveFailureCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveFailureCount, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastErrorAt orders the results by the last_error_at field.
func ByLastErrorAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorAt, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByProxyField orders the results by proxy field.
func ByProxyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxyStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderConfigField orders the results by provider_config field.
func ByProviderConfigField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderConfigStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, AccountTable, AccountColumn),
	)
}
func newProxyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProxyTable, ProxyColumn),
	)
}
func newProviderConfigStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderConfigInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderConfigTable, ProviderConfigColumn),
	)
}
