// Code generated by ent, DO NOT EDIT.

package managedproxylease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldAccountID, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldProxyID, v))
}

// ProviderConfigID applies equality check predicate on the "provider_config_id" field. It's identical to ProviderConfigIDEQ.
func ProviderConfigID(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldProviderConfigID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldSessionID, v))
}

// TargetCountry applies equality check predicate on the "target_country" field. It's identical to TargetCountryEQ.
func TargetCountry(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldTargetCountry, v))
}

// TargetState applies equality check predicate on the "target_state" field. It's identical to TargetStateEQ.
func TargetState(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldTargetState, v))
}

// TargetCity applies equality check predicate on the "target_city" field. It's identical to TargetCityEQ.
func TargetCity(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldTargetCity, v))
}

// Strict applies equality check predicate on the "strict" field. It's identical to StrictEQ.
func Strict(v bool) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldStrict, v))
}

// LifetimeMinutes applies equality check predicate on the "lifetime_minutes" field. It's identical to LifetimeMinutesEQ.
func LifetimeMinutes(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldLifetimeMinutes, v))
}

// HealthCheckedAt applies equality check predicate on the "health_checked_at" field. It's identical to HealthCheckedAtEQ.
func HealthCheckedAt(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldHealthCheckedAt, v))
}

// ObservedExitIP applies equality check predicate on the "observed_exit_ip" field. It's identical to ObservedExitIPEQ.
func ObservedExitIP(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedExitIP, v))
}

// ObservedCountry applies equality check predicate on the "observed_country" field. It's identical to ObservedCountryEQ.
func ObservedCountry(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedCountry, v))
}

// ObservedState applies equality check predicate on the "observed_state" field. It's identical to ObservedStateEQ.
func ObservedState(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedState, v))
}

// ObservedCity applies equality check predicate on the "observed_city" field. It's identical to ObservedCityEQ.
func ObservedCity(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedCity, v))
}

// ObservedLatencyMs applies equality check predicate on the "observed_latency_ms" field. It's identical to ObservedLatencyMsEQ.
func ObservedLatencyMs(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedLatencyMs, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldActivatedAt, v))
}

// LastRotatedAt applies equality check predicate on the "last_rotated_at" field. It's identical to LastRotatedAtEQ.
func LastRotatedAt(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldLastRotatedAt, v))
}

// NextRotationAt applies equality check predicate on the "next_rotation_at" field. It's identical to NextRotationAtEQ.
func NextRotationAt(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldNextRotationAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldExpiresAt, v))
}

// FailureCount applies equality check predicate on the "failure_count" field. It's identical to FailureCountEQ.
func FailureCount(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldFailureCount, v))
}

// ConsecutiveFailureCount applies equality check predicate on the "consecutive_failure_count" field. It's identical to ConsecutiveFailureCountEQ.
func ConsecutiveFailureCount(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldConsecutiveFailureCount, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldLastError, v))
}

// LastErrorAt applies equality check predicate on the "last_error_at" field. It's identical to LastErrorAtEQ.
func LastErrorAt(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldLastErrorAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldAccountID, vs...))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProviderConfigIDEQ applies the EQ predicate on the "provider_config_id" field.
func ProviderConfigIDEQ(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldProviderConfigID, v))
}

// ProviderConfigIDNEQ applies the NEQ predicate on the "provider_config_id" field.
func ProviderConfigIDNEQ(v int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldProviderConfigID, v))
}

// ProviderConfigIDIn applies the In predicate on the "provider_config_id" field.
func ProviderConfigIDIn(vs ...int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldProviderConfigID, vs...))
}

// ProviderConfigIDNotIn applies the NotIn predicate on the "provider_config_id" field.
func ProviderConfigIDNotIn(vs ...int64) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldProviderConfigID, vs...))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldSessionID, v))
}

// TargetCountryEQ applies the EQ predicate on the "target_country" field.
func TargetCountryEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldTargetCountry, v))
}

// TargetCountryNEQ applies the NEQ predicate on the "target_country" field.
func TargetCountryNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldTargetCountry, v))
}

// TargetCountryIn applies the In predicate on the "target_country" field.
func TargetCountryIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldTargetCountry, vs...))
}

// TargetCountryNotIn applies the NotIn predicate on the "target_country" field.
func TargetCountryNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldTargetCountry, vs...))
}

// TargetCountryGT applies the GT predicate on the "target_country" field.
func TargetCountryGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldTargetCountry, v))
}

// TargetCountryGTE applies the GTE predicate on the "target_country" field.
func TargetCountryGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldTargetCountry, v))
}

// TargetCountryLT applies the LT predicate on the "target_country" field.
func TargetCountryLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldTargetCountry, v))
}

// TargetCountryLTE applies the LTE predicate on the "target_country" field.
func TargetCountryLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldTargetCountry, v))
}

// TargetCountryContains applies the Contains predicate on the "target_country" field.
func TargetCountryContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldTargetCountry, v))
}

// TargetCountryHasPrefix applies the HasPrefix predicate on the "target_country" field.
func TargetCountryHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldTargetCountry, v))
}

// TargetCountryHasSuffix applies the HasSuffix predicate on the "target_country" field.
func TargetCountryHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldTargetCountry, v))
}

// TargetCountryIsNil applies the IsNil predicate on the "target_country" field.
func TargetCountryIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldTargetCountry))
}

// TargetCountryNotNil applies the NotNil predicate on the "target_country" field.
func TargetCountryNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldTargetCountry))
}

// TargetCountryEqualFold applies the EqualFold predicate on the "target_country" field.
func TargetCountryEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldTargetCountry, v))
}

// TargetCountryContainsFold applies the ContainsFold predicate on the "target_country" field.
func TargetCountryContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldTargetCountry, v))
}

// TargetStateEQ applies the EQ predicate on the "target_state" field.
func TargetStateEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldTargetState, v))
}

// TargetStateNEQ applies the NEQ predicate on the "target_state" field.
func TargetStateNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldTargetState, v))
}

// TargetStateIn applies the In predicate on the "target_state" field.
func TargetStateIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldTargetState, vs...))
}

// TargetStateNotIn applies the NotIn predicate on the "target_state" field.
func TargetStateNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldTargetState, vs...))
}

// TargetStateGT applies the GT predicate on the "target_state" field.
func TargetStateGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldTargetState, v))
}

// TargetStateGTE applies the GTE predicate on the "target_state" field.
func TargetStateGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldTargetState, v))
}

// TargetStateLT applies the LT predicate on the "target_state" field.
func TargetStateLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldTargetState, v))
}

// TargetStateLTE applies the LTE predicate on the "target_state" field.
func TargetStateLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldTargetState, v))
}

// TargetStateContains applies the Contains predicate on the "target_state" field.
func TargetStateContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldTargetState, v))
}

// TargetStateHasPrefix applies the HasPrefix predicate on the "target_state" field.
func TargetStateHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldTargetState, v))
}

// TargetStateHasSuffix applies the HasSuffix predicate on the "target_state" field.
func TargetStateHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldTargetState, v))
}

// TargetStateIsNil applies the IsNil predicate on the "target_state" field.
func TargetStateIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldTargetState))
}

// TargetStateNotNil applies the NotNil predicate on the "target_state" field.
func TargetStateNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldTargetState))
}

// TargetStateEqualFold applies the EqualFold predicate on the "target_state" field.
func TargetStateEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldTargetState, v))
}

// TargetStateContainsFold applies the ContainsFold predicate on the "target_state" field.
func TargetStateContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldTargetState, v))
}

// TargetCityEQ applies the EQ predicate on the "target_city" field.
func TargetCityEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldTargetCity, v))
}

// TargetCityNEQ applies the NEQ predicate on the "target_city" field.
func TargetCityNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldTargetCity, v))
}

// TargetCityIn applies the In predicate on the "target_city" field.
func TargetCityIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldTargetCity, vs...))
}

// TargetCityNotIn applies the NotIn predicate on the "target_city" field.
func TargetCityNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldTargetCity, vs...))
}

// TargetCityGT applies the GT predicate on the "target_city" field.
func TargetCityGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldTargetCity, v))
}

// TargetCityGTE applies the GTE predicate on the "target_city" field.
func TargetCityGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldTargetCity, v))
}

// TargetCityLT applies the LT predicate on the "target_city" field.
func TargetCityLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldTargetCity, v))
}

// TargetCityLTE applies the LTE predicate on the "target_city" field.
func TargetCityLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldTargetCity, v))
}

// TargetCityContains applies the Contains predicate on the "target_city" field.
func TargetCityContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldTargetCity, v))
}

// TargetCityHasPrefix applies the HasPrefix predicate on the "target_city" field.
func TargetCityHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldTargetCity, v))
}

// TargetCityHasSuffix applies the HasSuffix predicate on the "target_city" field.
func TargetCityHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldTargetCity, v))
}

// TargetCityIsNil applies the IsNil predicate on the "target_city" field.
func TargetCityIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldTargetCity))
}

// TargetCityNotNil applies the NotNil predicate on the "target_city" field.
func TargetCityNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldTargetCity))
}

// TargetCityEqualFold applies the EqualFold predicate on the "target_city" field.
func TargetCityEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldTargetCity, v))
}

// TargetCityContainsFold applies the ContainsFold predicate on the "target_city" field.
func TargetCityContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldTargetCity, v))
}

// StrictEQ applies the EQ predicate on the "strict" field.
func StrictEQ(v bool) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldStrict, v))
}

// StrictNEQ applies the NEQ predicate on the "strict" field.
func StrictNEQ(v bool) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldStrict, v))
}

// LifetimeMinutesEQ applies the EQ predicate on the "lifetime_minutes" field.
func LifetimeMinutesEQ(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldLifetimeMinutes, v))
}

// LifetimeMinutesNEQ applies the NEQ predicate on the "lifetime_minutes" field.
func LifetimeMinutesNEQ(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldLifetimeMinutes, v))
}

// LifetimeMinutesIn applies the In predicate on the "lifetime_minutes" field.
func LifetimeMinutesIn(vs ...int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldLifetimeMinutes, vs...))
}

// LifetimeMinutesNotIn applies the NotIn predicate on the "lifetime_minutes" field.
func LifetimeMinutesNotIn(vs ...int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldLifetimeMinutes, vs...))
}

// LifetimeMinutesGT applies the GT predicate on the "lifetime_minutes" field.
func LifetimeMinutesGT(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldLifetimeMinutes, v))
}

// LifetimeMinutesGTE applies the GTE predicate on the "lifetime_minutes" field.
func LifetimeMinutesGTE(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldLifetimeMinutes, v))
}

// LifetimeMinutesLT applies the LT predicate on the "lifetime_minutes" field.
func LifetimeMinutesLT(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldLifetimeMinutes, v))
}

// LifetimeMinutesLTE applies the LTE predicate on the "lifetime_minutes" field.
func LifetimeMinutesLTE(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldLifetimeMinutes, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldState, vs...))
}

// HealthStatusEQ applies the EQ predicate on the "health_status" field.
func HealthStatusEQ(v HealthStatus) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldHealthStatus, v))
}

// HealthStatusNEQ applies the NEQ predicate on the "health_status" field.
func HealthStatusNEQ(v HealthStatus) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldHealthStatus, v))
}

// HealthStatusIn applies the In predicate on the "health_status" field.
func HealthStatusIn(vs ...HealthStatus) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldHealthStatus, vs...))
}

// HealthStatusNotIn applies the NotIn predicate on the "health_status" field.
func HealthStatusNotIn(vs ...HealthStatus) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldHealthStatus, vs...))
}

// HealthCheckedAtEQ applies the EQ predicate on the "health_checked_at" field.
func HealthCheckedAtEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldHealthCheckedAt, v))
}

// HealthCheckedAtNEQ applies the NEQ predicate on the "health_checked_at" field.
func HealthCheckedAtNEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldHealthCheckedAt, v))
}

// HealthCheckedAtIn applies the In predicate on the "health_checked_at" field.
func HealthCheckedAtIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldHealthCheckedAt, vs...))
}

// HealthCheckedAtNotIn applies the NotIn predicate on the "health_checked_at" field.
func HealthCheckedAtNotIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldHealthCheckedAt, vs...))
}

// HealthCheckedAtGT applies the GT predicate on the "health_checked_at" field.
func HealthCheckedAtGT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldHealthCheckedAt, v))
}

// HealthCheckedAtGTE applies the GTE predicate on the "health_checked_at" field.
func HealthCheckedAtGTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldHealthCheckedAt, v))
}

// HealthCheckedAtLT applies the LT predicate on the "health_checked_at" field.
func HealthCheckedAtLT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldHealthCheckedAt, v))
}

// HealthCheckedAtLTE applies the LTE predicate on the "health_checked_at" field.
func HealthCheckedAtLTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldHealthCheckedAt, v))
}

// HealthCheckedAtIsNil applies the IsNil predicate on the "health_checked_at" field.
func HealthCheckedAtIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldHealthCheckedAt))
}

// HealthCheckedAtNotNil applies the NotNil predicate on the "health_checked_at" field.
func HealthCheckedAtNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldHealthCheckedAt))
}

// ObservedExitIPEQ applies the EQ predicate on the "observed_exit_ip" field.
func ObservedExitIPEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedExitIP, v))
}

// ObservedExitIPNEQ applies the NEQ predicate on the "observed_exit_ip" field.
func ObservedExitIPNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldObservedExitIP, v))
}

// ObservedExitIPIn applies the In predicate on the "observed_exit_ip" field.
func ObservedExitIPIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldObservedExitIP, vs...))
}

// ObservedExitIPNotIn applies the NotIn predicate on the "observed_exit_ip" field.
func ObservedExitIPNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldObservedExitIP, vs...))
}

// ObservedExitIPGT applies the GT predicate on the "observed_exit_ip" field.
func ObservedExitIPGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldObservedExitIP, v))
}

// ObservedExitIPGTE applies the GTE predicate on the "observed_exit_ip" field.
func ObservedExitIPGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldObservedExitIP, v))
}

// ObservedExitIPLT applies the LT predicate on the "observed_exit_ip" field.
func ObservedExitIPLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldObservedExitIP, v))
}

// ObservedExitIPLTE applies the LTE predicate on the "observed_exit_ip" field.
func ObservedExitIPLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldObservedExitIP, v))
}

// ObservedExitIPContains applies the Contains predicate on the "observed_exit_ip" field.
func ObservedExitIPContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldObservedExitIP, v))
}

// ObservedExitIPHasPrefix applies the HasPrefix predicate on the "observed_exit_ip" field.
func ObservedExitIPHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldObservedExitIP, v))
}

// ObservedExitIPHasSuffix applies the HasSuffix predicate on the "observed_exit_ip" field.
func ObservedExitIPHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldObservedExitIP, v))
}

// ObservedExitIPIsNil applies the IsNil predicate on the "observed_exit_ip" field.
func ObservedExitIPIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldObservedExitIP))
}

// ObservedExitIPNotNil applies the NotNil predicate on the "observed_exit_ip" field.
func ObservedExitIPNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldObservedExitIP))
}

// ObservedExitIPEqualFold applies the EqualFold predicate on the "observed_exit_ip" field.
func ObservedExitIPEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldObservedExitIP, v))
}

// ObservedExitIPContainsFold applies the ContainsFold predicate on the "observed_exit_ip" field.
func ObservedExitIPContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldObservedExitIP, v))
}

// ObservedCountryEQ applies the EQ predicate on the "observed_country" field.
func ObservedCountryEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedCountry, v))
}

// ObservedCountryNEQ applies the NEQ predicate on the "observed_country" field.
func ObservedCountryNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldObservedCountry, v))
}

// ObservedCountryIn applies the In predicate on the "observed_country" field.
func ObservedCountryIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldObservedCountry, vs...))
}

// ObservedCountryNotIn applies the NotIn predicate on the "observed_country" field.
func ObservedCountryNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldObservedCountry, vs...))
}

// ObservedCountryGT applies the GT predicate on the "observed_country" field.
func ObservedCountryGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldObservedCountry, v))
}

// ObservedCountryGTE applies the GTE predicate on the "observed_country" field.
func ObservedCountryGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldObservedCountry, v))
}

// ObservedCountryLT applies the LT predicate on the "observed_country" field.
func ObservedCountryLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldObservedCountry, v))
}

// ObservedCountryLTE applies the LTE predicate on the "observed_country" field.
func ObservedCountryLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldObservedCountry, v))
}

// ObservedCountryContains applies the Contains predicate on the "observed_country" field.
func ObservedCountryContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldObservedCountry, v))
}

// ObservedCountryHasPrefix applies the HasPrefix predicate on the "observed_country" field.
func ObservedCountryHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldObservedCountry, v))
}

// ObservedCountryHasSuffix applies the HasSuffix predicate on the "observed_country" field.
func ObservedCountryHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldObservedCountry, v))
}

// ObservedCountryIsNil applies the IsNil predicate on the "observed_country" field.
func ObservedCountryIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldObservedCountry))
}

// ObservedCountryNotNil applies the NotNil predicate on the "observed_country" field.
func ObservedCountryNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldObservedCountry))
}

// ObservedCountryEqualFold applies the EqualFold predicate on the "observed_country" field.
func ObservedCountryEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldObservedCountry, v))
}

// ObservedCountryContainsFold applies the ContainsFold predicate on the "observed_country" field.
func ObservedCountryContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldObservedCountry, v))
}

// ObservedStateEQ applies the EQ predicate on the "observed_state" field.
func ObservedStateEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedState, v))
}

// ObservedStateNEQ applies the NEQ predicate on the "observed_state" field.
func ObservedStateNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldObservedState, v))
}

// ObservedStateIn applies the In predicate on the "observed_state" field.
func ObservedStateIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldObservedState, vs...))
}

// ObservedStateNotIn applies the NotIn predicate on the "observed_state" field.
func ObservedStateNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldObservedState, vs...))
}

// ObservedStateGT applies the GT predicate on the "observed_state" field.
func ObservedStateGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldObservedState, v))
}

// ObservedStateGTE applies the GTE predicate on the "observed_state" field.
func ObservedStateGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldObservedState, v))
}

// ObservedStateLT applies the LT predicate on the "observed_state" field.
func ObservedStateLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldObservedState, v))
}

// ObservedStateLTE applies the LTE predicate on the "observed_state" field.
func ObservedStateLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldObservedState, v))
}

// ObservedStateContains applies the Contains predicate on the "observed_state" field.
func ObservedStateContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldObservedState, v))
}

// ObservedStateHasPrefix applies the HasPrefix predicate on the "observed_state" field.
func ObservedStateHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldObservedState, v))
}

// ObservedStateHasSuffix applies the HasSuffix predicate on the "observed_state" field.
func ObservedStateHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldObservedState, v))
}

// ObservedStateIsNil applies the IsNil predicate on the "observed_state" field.
func ObservedStateIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldObservedState))
}

// ObservedStateNotNil applies the NotNil predicate on the "observed_state" field.
func ObservedStateNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldObservedState))
}

// ObservedStateEqualFold applies the EqualFold predicate on the "observed_state" field.
func ObservedStateEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldObservedState, v))
}

// ObservedStateContainsFold applies the ContainsFold predicate on the "observed_state" field.
func ObservedStateContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldObservedState, v))
}

// ObservedCityEQ applies the EQ predicate on the "observed_city" field.
func ObservedCityEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedCity, v))
}

// ObservedCityNEQ applies the NEQ predicate on the "observed_city" field.
func ObservedCityNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldObservedCity, v))
}

// ObservedCityIn applies the In predicate on the "observed_city" field.
func ObservedCityIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldObservedCity, vs...))
}

// ObservedCityNotIn applies the NotIn predicate on the "observed_city" field.
func ObservedCityNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldObservedCity, vs...))
}

// ObservedCityGT applies the GT predicate on the "observed_city" field.
func ObservedCityGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldObservedCity, v))
}

// ObservedCityGTE applies the GTE predicate on the "observed_city" field.
func ObservedCityGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldObservedCity, v))
}

// ObservedCityLT applies the LT predicate on the "observed_city" field.
func ObservedCityLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldObservedCity, v))
}

// ObservedCityLTE applies the LTE predicate on the "observed_city" field.
func ObservedCityLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldObservedCity, v))
}

// ObservedCityContains applies the Contains predicate on the "observed_city" field.
func ObservedCityContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldObservedCity, v))
}

// ObservedCityHasPrefix applies the HasPrefix predicate on the "observed_city" field.
func ObservedCityHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldObservedCity, v))
}

// ObservedCityHasSuffix applies the HasSuffix predicate on the "observed_city" field.
func ObservedCityHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldObservedCity, v))
}

// ObservedCityIsNil applies the IsNil predicate on the "observed_city" field.
func ObservedCityIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldObservedCity))
}

// ObservedCityNotNil applies the NotNil predicate on the "observed_city" field.
func ObservedCityNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldObservedCity))
}

// ObservedCityEqualFold applies the EqualFold predicate on the "observed_city" field.
func ObservedCityEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldObservedCity, v))
}

// ObservedCityContainsFold applies the ContainsFold predicate on the "observed_city" field.
func ObservedCityContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldObservedCity, v))
}

// ObservedLatencyMsEQ applies the EQ predicate on the "observed_latency_ms" field.
func ObservedLatencyMsEQ(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldObservedLatencyMs, v))
}

// ObservedLatencyMsNEQ applies the NEQ predicate on the "observed_latency_ms" field.
func ObservedLatencyMsNEQ(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldObservedLatencyMs, v))
}

// ObservedLatencyMsIn applies the In predicate on the "observed_latency_ms" field.
func ObservedLatencyMsIn(vs ...int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldObservedLatencyMs, vs...))
}

// ObservedLatencyMsNotIn applies the NotIn predicate on the "observed_latency_ms" field.
func ObservedLatencyMsNotIn(vs ...int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldObservedLatencyMs, vs...))
}

// ObservedLatencyMsGT applies the GT predicate on the "observed_latency_ms" field.
func ObservedLatencyMsGT(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldObservedLatencyMs, v))
}

// ObservedLatencyMsGTE applies the GTE predicate on the "observed_latency_ms" field.
func ObservedLatencyMsGTE(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldObservedLatencyMs, v))
}

// ObservedLatencyMsLT applies the LT predicate on the "observed_latency_ms" field.
func ObservedLatencyMsLT(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldObservedLatencyMs, v))
}

// ObservedLatencyMsLTE applies the LTE predicate on the "observed_latency_ms" field.
func ObservedLatencyMsLTE(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldObservedLatencyMs, v))
}

// ObservedLatencyMsIsNil applies the IsNil predicate on the "observed_latency_ms" field.
func ObservedLatencyMsIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldObservedLatencyMs))
}

// ObservedLatencyMsNotNil applies the NotNil predicate on the "observed_latency_ms" field.
func ObservedLatencyMsNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldObservedLatencyMs))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldActivatedAt, v))
}

// ActivatedAtIsNil applies the IsNil predicate on the "activated_at" field.
func ActivatedAtIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldActivatedAt))
}

// ActivatedAtNotNil applies the NotNil predicate on the "activated_at" field.
func ActivatedAtNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldActivatedAt))
}

// LastRotatedAtEQ applies the EQ predicate on the "last_rotated_at" field.
func LastRotatedAtEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldLastRotatedAt, v))
}

// LastRotatedAtNEQ applies the NEQ predicate on the "last_rotated_at" field.
func LastRotatedAtNEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldLastRotatedAt, v))
}

// LastRotatedAtIn applies the In predicate on the "last_rotated_at" field.
func LastRotatedAtIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldLastRotatedAt, vs...))
}

// LastRotatedAtNotIn applies the NotIn predicate on the "last_rotated_at" field.
func LastRotatedAtNotIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldLastRotatedAt, vs...))
}

// LastRotatedAtGT applies the GT predicate on the "last_rotated_at" field.
func LastRotatedAtGT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldLastRotatedAt, v))
}

// LastRotatedAtGTE applies the GTE predicate on the "last_rotated_at" field.
func LastRotatedAtGTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldLastRotatedAt, v))
}

// LastRotatedAtLT applies the LT predicate on the "last_rotated_at" field.
func LastRotatedAtLT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldLastRotatedAt, v))
}

// LastRotatedAtLTE applies the LTE predicate on the "last_rotated_at" field.
func LastRotatedAtLTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldLastRotatedAt, v))
}

// LastRotatedAtIsNil applies the IsNil predicate on the "last_rotated_at" field.
func LastRotatedAtIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldLastRotatedAt))
}

// LastRotatedAtNotNil applies the NotNil predicate on the "last_rotated_at" field.
func LastRotatedAtNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldLastRotatedAt))
}

// NextRotationAtEQ applies the EQ predicate on the "next_rotation_at" field.
func NextRotationAtEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldNextRotationAt, v))
}

// NextRotationAtNEQ applies the NEQ predicate on the "next_rotation_at" field.
func NextRotationAtNEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldNextRotationAt, v))
}

// NextRotationAtIn applies the In predicate on the "next_rotation_at" field.
func NextRotationAtIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldNextRotationAt, vs...))
}

// NextRotationAtNotIn applies the NotIn predicate on the "next_rotation_at" field.
func NextRotationAtNotIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldNextRotationAt, vs...))
}

// NextRotationAtGT applies the GT predicate on the "next_rotation_at" field.
func NextRotationAtGT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldNextRotationAt, v))
}

// NextRotationAtGTE applies the GTE predicate on the "next_rotation_at" field.
func NextRotationAtGTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldNextRotationAt, v))
}

// NextRotationAtLT applies the LT predicate on the "next_rotation_at" field.
func NextRotationAtLT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldNextRotationAt, v))
}

// NextRotationAtLTE applies the LTE predicate on the "next_rotation_at" field.
func NextRotationAtLTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldNextRotationAt, v))
}

// NextRotationAtIsNil applies the IsNil predicate on the "next_rotation_at" field.
func NextRotationAtIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldNextRotationAt))
}

// NextRotationAtNotNil applies the NotNil predicate on the "next_rotation_at" field.
func NextRotationAtNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldNextRotationAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldExpiresAt))
}

// FailureCountEQ applies the EQ predicate on the "failure_count" field.
func FailureCountEQ(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldFailureCount, v))
}

// FailureCountNEQ applies the NEQ predicate on the "failure_count" field.
func FailureCountNEQ(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldFailureCount, v))
}

// FailureCountIn applies the In predicate on the "failure_count" field.
func FailureCountIn(vs ...int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldFailureCount, vs...))
}

// FailureCountNotIn applies the NotIn predicate on the "failure_count" field.
func FailureCountNotIn(vs ...int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldFailureCount, vs...))
}

// FailureCountGT applies the GT predicate on the "failure_count" field.
func FailureCountGT(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldFailureCount, v))
}

// FailureCountGTE applies the GTE predicate on the "failure_count" field.
func FailureCountGTE(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldFailureCount, v))
}

// FailureCountLT applies the LT predicate on the "failure_count" field.
func FailureCountLT(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldFailureCount, v))
}

// FailureCountLTE applies the LTE predicate on the "failure_count" field.
func FailureCountLTE(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldFailureCount, v))
}

// ConsecutiveFailureCountEQ applies the EQ predicate on the "consecutive_failure_count" field.
func ConsecutiveFailureCountEQ(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldConsecutiveFailureCount, v))
}

// ConsecutiveFailureCountNEQ applies the NEQ predicate on the "consecutive_failure_count" field.
func ConsecutiveFailureCountNEQ(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldConsecutiveFailureCount, v))
}

// ConsecutiveFailureCountIn applies the In predicate on the "consecutive_failure_count" field.
func ConsecutiveFailureCountIn(vs ...int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldConsecutiveFailureCount, vs...))
}

// ConsecutiveFailureCountNotIn applies the NotIn predicate on the "consecutive_failure_count" field.
func ConsecutiveFailureCountNotIn(vs ...int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldConsecutiveFailureCount, vs...))
}

// ConsecutiveFailureCountGT applies the GT predicate on the "consecutive_failure_count" field.
func ConsecutiveFailureCountGT(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldConsecutiveFailureCount, v))
}

// ConsecutiveFailureCountGTE applies the GTE predicate on the "consecutive_failure_count" field.
func ConsecutiveFailureCountGTE(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldConsecutiveFailureCount, v))
}

// ConsecutiveFailureCountLT applies the LT predicate on the "consecutive_failure_count" field.
func ConsecutiveFailureCountLT(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldConsecutiveFailureCount, v))
}

// ConsecutiveFailureCountLTE applies the LTE predicate on the "consecutive_failure_count" field.
func ConsecutiveFailureCountLTE(v int) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldConsecutiveFailureCount, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldContainsFold(FieldLastError, v))
}

// LastErrorAtEQ applies the EQ predicate on the "last_error_at" field.
func LastErrorAtEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldEQ(FieldLastErrorAt, v))
}

// LastErrorAtNEQ applies the NEQ predicate on the "last_error_at" field.
func LastErrorAtNEQ(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNEQ(FieldLastErrorAt, v))
}

// LastErrorAtIn applies the In predicate on the "last_error_at" field.
func LastErrorAtIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIn(FieldLastErrorAt, vs...))
}

// LastErrorAtNotIn applies the NotIn predicate on the "last_error_at" field.
func LastErrorAtNotIn(vs ...time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotIn(FieldLastErrorAt, vs...))
}

// LastErrorAtGT applies the GT predicate on the "last_error_at" field.
func LastErrorAtGT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGT(FieldLastErrorAt, v))
}

// LastErrorAtGTE applies the GTE predicate on the "last_error_at" field.
func LastErrorAtGTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldGTE(FieldLastErrorAt, v))
}

// LastErrorAtLT applies the LT predicate on the "last_error_at" field.
func LastErrorAtLT(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLT(FieldLastErrorAt, v))
}

// LastErrorAtLTE applies the LTE predicate on the "last_error_at" field.
func LastErrorAtLTE(v time.Time) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldLTE(FieldLastErrorAt, v))
}

// LastErrorAtIsNil applies the IsNil predicate on the "last_error_at" field.
func LastErrorAtIsNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldIsNull(FieldLastErrorAt))
}

// LastErrorAtNotNil applies the NotNil predicate on the "last_error_at" field.
func LastErrorAtNotNil() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.FieldNotNull(FieldLastErrorAt))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderConfig applies the HasEdge predicate on the "provider_config" edge.
func HasProviderConfig() predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderConfigTable, ProviderConfigColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderConfigWith applies the HasEdge predicate on the "provider_config" edge with a given conditions (other predicates).
func HasProviderConfigWith(preds ...predicate.CatProxyProviderConfig) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(func(s *sql.Selector) {
		step := newProviderConfigStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ManagedProxyLease) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ManagedProxyLease) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ManagedProxyLease) predicate.ManagedProxyLease {
	return predicate.ManagedProxyLease(sql.NotPredicates(p))
}
