// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/catproxyproviderconfig"
	"github.com/Wei-Shaw/sub2api/ent/managedproxylease"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CatProxyProviderConfigUpdate is the builder for updating CatProxyProviderConfig entities.
type CatProxyProviderConfigUpdate struct {
	config
	hooks    []Hook
	mutation *CatProxyProviderConfigMutation
}

// Where appends a list predicates to the CatProxyProviderConfigUpdate builder.
func (_u *CatProxyProviderConfigUpdate) Where(ps ...predicate.CatProxyProviderConfig) *CatProxyProviderConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CatProxyProviderConfigUpdate) SetUpdatedAt(v time.Time) *CatProxyProviderConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CatProxyProviderConfigUpdate) SetName(v string) *CatProxyProviderConfigUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableName(v *string) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *CatProxyProviderConfigUpdate) SetProviderType(v catproxyproviderconfig.ProviderType) *CatProxyProviderConfigUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableProviderType(v *catproxyproviderconfig.ProviderType) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CatProxyProviderConfigUpdate) SetStatus(v catproxyproviderconfig.Status) *CatProxyProviderConfigUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableStatus(v *catproxyproviderconfig.Status) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *CatProxyProviderConfigUpdate) SetIsDefault(v bool) *CatProxyProviderConfigUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableIsDefault(v *bool) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *CatProxyProviderConfigUpdate) SetProtocol(v catproxyproviderconfig.Protocol) *CatProxyProviderConfigUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableProtocol(v *catproxyproviderconfig.Protocol) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *CatProxyProviderConfigUpdate) SetHost(v string) *CatProxyProviderConfigUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableHost(v *string) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetBaseUsername sets the "base_username" field.
func (_u *CatProxyProviderConfigUpdate) SetBaseUsername(v string) *CatProxyProviderConfigUpdate {
	_u.mutation.SetBaseUsername(v)
	return _u
}

// SetNillableBaseUsername sets the "base_username" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableBaseUsername(v *string) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetBaseUsername(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *CatProxyProviderConfigUpdate) SetPassword(v string) *CatProxyProviderConfigUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillablePassword(v *string) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetDefaultCountry sets the "default_country" field.
func (_u *CatProxyProviderConfigUpdate) SetDefaultCountry(v string) *CatProxyProviderConfigUpdate {
	_u.mutation.SetDefaultCountry(v)
	return _u
}

// SetNillableDefaultCountry sets the "default_country" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableDefaultCountry(v *string) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetDefaultCountry(*v)
	}
	return _u
}

// ClearDefaultCountry clears the value of the "default_country" field.
func (_u *CatProxyProviderConfigUpdate) ClearDefaultCountry() *CatProxyProviderConfigUpdate {
	_u.mutation.ClearDefaultCountry()
	return _u
}

// SetDefaultState sets the "default_state" field.
func (_u *CatProxyProviderConfigUpdate) SetDefaultState(v string) *CatProxyProviderConfigUpdate {
	_u.mutation.SetDefaultState(v)
	return _u
}

// SetNillableDefaultState sets the "default_state" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableDefaultState(v *string) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetDefaultState(*v)
	}
	return _u
}

// ClearDefaultState clears the value of the "default_state" field.
func (_u *CatProxyProviderConfigUpdate) ClearDefaultState() *CatProxyProviderConfigUpdate {
	_u.mutation.ClearDefaultState()
	return _u
}

// SetDefaultCity sets the "default_city" field.
func (_u *CatProxyProviderConfigUpdate) SetDefaultCity(v string) *CatProxyProviderConfigUpdate {
	_u.mutation.SetDefaultCity(v)
	return _u
}

// SetNillableDefaultCity sets the "default_city" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableDefaultCity(v *string) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetDefaultCity(*v)
	}
	return _u
}

// ClearDefaultCity clears the value of the "default_city" field.
func (_u *CatProxyProviderConfigUpdate) ClearDefaultCity() *CatProxyProviderConfigUpdate {
	_u.mutation.ClearDefaultCity()
	return _u
}

// SetLifetimeMinutes sets the "lifetime_minutes" field.
func (_u *CatProxyProviderConfigUpdate) SetLifetimeMinutes(v int) *CatProxyProviderConfigUpdate {
	_u.mutation.ResetLifetimeMinutes()
	_u.mutation.SetLifetimeMinutes(v)
	return _u
}

// SetNillableLifetimeMinutes sets the "lifetime_minutes" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableLifetimeMinutes(v *int) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetLifetimeMinutes(*v)
	}
	return _u
}

// AddLifetimeMinutes adds value to the "lifetime_minutes" field.
func (_u *CatProxyProviderConfigUpdate) AddLifetimeMinutes(v int) *CatProxyProviderConfigUpdate {
	_u.mutation.AddLifetimeMinutes(v)
	return _u
}

// SetStrict sets the "strict" field.
func (_u *CatProxyProviderConfigUpdate) SetStrict(v bool) *CatProxyProviderConfigUpdate {
	_u.mutation.SetStrict(v)
	return _u
}

// SetNillableStrict sets the "strict" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableStrict(v *bool) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetStrict(*v)
	}
	return _u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_u *CatProxyProviderConfigUpdate) SetLastProbeAt(v time.Time) *CatProxyProviderConfigUpdate {
	_u.mutation.SetLastProbeAt(v)
	return _u
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableLastProbeAt(v *time.Time) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetLastProbeAt(*v)
	}
	return _u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (_u *CatProxyProviderConfigUpdate) ClearLastProbeAt() *CatProxyProviderConfigUpdate {
	_u.mutation.ClearLastProbeAt()
	return _u
}

// SetLastProbeLatencyMs sets the "last_probe_latency_ms" field.
func (_u *CatProxyProviderConfigUpdate) SetLastProbeLatencyMs(v int) *CatProxyProviderConfigUpdate {
	_u.mutation.ResetLastProbeLatencyMs()
	_u.mutation.SetLastProbeLatencyMs(v)
	return _u
}

// SetNillableLastProbeLatencyMs sets the "last_probe_latency_ms" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableLastProbeLatencyMs(v *int) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetLastProbeLatencyMs(*v)
	}
	return _u
}

// AddLastProbeLatencyMs adds value to the "last_probe_latency_ms" field.
func (_u *CatProxyProviderConfigUpdate) AddLastProbeLatencyMs(v int) *CatProxyProviderConfigUpdate {
	_u.mutation.AddLastProbeLatencyMs(v)
	return _u
}

// ClearLastProbeLatencyMs clears the value of the "last_probe_latency_ms" field.
func (_u *CatProxyProviderConfigUpdate) ClearLastProbeLatencyMs() *CatProxyProviderConfigUpdate {
	_u.mutation.ClearLastProbeLatencyMs()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CatProxyProviderConfigUpdate) SetLastError(v string) *CatProxyProviderConfigUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableLastError(v *string) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CatProxyProviderConfigUpdate) ClearLastError() *CatProxyProviderConfigUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastErrorAt sets the "last_error_at" field.
func (_u *CatProxyProviderConfigUpdate) SetLastErrorAt(v time.Time) *CatProxyProviderConfigUpdate {
	_u.mutation.SetLastErrorAt(v)
	return _u
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdate) SetNillableLastErrorAt(v *time.Time) *CatProxyProviderConfigUpdate {
	if v != nil {
		_u.SetLastErrorAt(*v)
	}
	return _u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (_u *CatProxyProviderConfigUpdate) ClearLastErrorAt() *CatProxyProviderConfigUpdate {
	_u.mutation.ClearLastErrorAt()
	return _u
}

// AddLeaseIDs adds the "leases" edge to the ManagedProxyLease entity by IDs.
func (_u *CatProxyProviderConfigUpdate) AddLeaseIDs(ids ...int64) *CatProxyProviderConfigUpdate {
	_u.mutation.AddLeaseIDs(ids...)
	return _u
}

// AddLeases adds the "leases" edges to the ManagedProxyLease entity.
func (_u *CatProxyProviderConfigUpdate) AddLeases(v ...*ManagedProxyLease) *CatProxyProviderConfigUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaseIDs(ids...)
}

// Mutation returns the CatProxyProviderConfigMutation object of the builder.
func (_u *CatProxyProviderConfigUpdate) Mutation() *CatProxyProviderConfigMutation {
	return _u.mutation
}

// ClearLeases clears all "leases" edges to the ManagedProxyLease entity.
func (_u *CatProxyProviderConfigUpdate) ClearLeases() *CatProxyProviderConfigUpdate {
	_u.mutation.ClearLeases()
	return _u
}

// RemoveLeaseIDs removes the "leases" edge to ManagedProxyLease entities by IDs.
func (_u *CatProxyProviderConfigUpdate) RemoveLeaseIDs(ids ...int64) *CatProxyProviderConfigUpdate {
	_u.mutation.RemoveLeaseIDs(ids...)
	return _u
}

// RemoveLeases removes "leases" edges to ManagedProxyLease entities.
func (_u *CatProxyProviderConfigUpdate) RemoveLeases(v ...*ManagedProxyLease) *CatProxyProviderConfigUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaseIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CatProxyProviderConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatProxyProviderConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CatProxyProviderConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatProxyProviderConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CatProxyProviderConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := catproxyproviderconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CatProxyProviderConfigUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := catproxyproviderconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := catproxyproviderconfig.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := catproxyproviderconfig.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := catproxyproviderconfig.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := catproxyproviderconfig.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseUsername(); ok {
		if err := catproxyproviderconfig.BaseUsernameValidator(v); err != nil {
			return &ValidationError{Name: "base_username", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.base_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := catproxyproviderconfig.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultCountry(); ok {
		if err := catproxyproviderconfig.DefaultCountryValidator(v); err != nil {
			return &ValidationError{Name: "default_country", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.default_country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultState(); ok {
		if err := catproxyproviderconfig.DefaultStateValidator(v); err != nil {
			return &ValidationError{Name: "default_state", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.default_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultCity(); ok {
		if err := catproxyproviderconfig.DefaultCityValidator(v); err != nil {
			return &ValidationError{Name: "default_city", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.default_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeMinutes(); ok {
		if err := catproxyproviderconfig.LifetimeMinutesValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_minutes", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.lifetime_minutes": %w`, err)}
		}
	}
	return nil
}

func (_u *CatProxyProviderConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(catproxyproviderconfig.Table, catproxyproviderconfig.Columns, sqlgraph.NewFieldSpec(catproxyproviderconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(catproxyproviderconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(catproxyproviderconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(catproxyproviderconfig.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(catproxyproviderconfig.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(catproxyproviderconfig.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(catproxyproviderconfig.FieldProtocol, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(catproxyproviderconfig.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseUsername(); ok {
		_spec.SetField(catproxyproviderconfig.FieldBaseUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(catproxyproviderconfig.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultCountry(); ok {
		_spec.SetField(catproxyproviderconfig.FieldDefaultCountry, field.TypeString, value)
	}
	if _u.mutation.DefaultCountryCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldDefaultCountry, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultState(); ok {
		_spec.SetField(catproxyproviderconfig.FieldDefaultState, field.TypeString, value)
	}
	if _u.mutation.DefaultStateCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldDefaultState, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultCity(); ok {
		_spec.SetField(catproxyproviderconfig.FieldDefaultCity, field.TypeString, value)
	}
	if _u.mutation.DefaultCityCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldDefaultCity, field.TypeString)
	}
	if value, ok := _u.mutation.LifetimeMinutes(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLifetimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLifetimeMinutes(); ok {
		_spec.AddField(catproxyproviderconfig.FieldLifetimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Strict(); ok {
		_spec.SetField(catproxyproviderconfig.FieldStrict, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastProbeAt(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLastProbeAt, field.TypeTime, value)
	}
	if _u.mutation.LastProbeAtCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldLastProbeAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProbeLatencyMs(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLastProbeLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastProbeLatencyMs(); ok {
		_spec.AddField(catproxyproviderconfig.FieldLastProbeLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LastProbeLatencyMsCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldLastProbeLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorAt(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLastErrorAt, field.TypeTime, value)
	}
	if _u.mutation.LastErrorAtCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldLastErrorAt, field.TypeTime)
	}
	if _u.mutation.LeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   catproxyproviderconfig.LeasesTable,
			Columns: []string{catproxyproviderconfig.LeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeasesIDs(); len(nodes) > 0 && !_u.mutation.LeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   catproxyproviderconfig.LeasesTable,
			Columns: []string{catproxyproviderconfig.LeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   catproxyproviderconfig.LeasesTable,
			Columns: []string{catproxyproviderconfig.LeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catproxyproviderconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CatProxyProviderConfigUpdateOne is the builder for updating a single CatProxyProviderConfig entity.
type CatProxyProviderConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CatProxyProviderConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CatProxyProviderConfigUpdateOne) SetUpdatedAt(v time.Time) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CatProxyProviderConfigUpdateOne) SetName(v string) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableName(v *string) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *CatProxyProviderConfigUpdateOne) SetProviderType(v catproxyproviderconfig.ProviderType) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableProviderType(v *catproxyproviderconfig.ProviderType) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CatProxyProviderConfigUpdateOne) SetStatus(v catproxyproviderconfig.Status) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableStatus(v *catproxyproviderconfig.Status) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *CatProxyProviderConfigUpdateOne) SetIsDefault(v bool) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableIsDefault(v *bool) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *CatProxyProviderConfigUpdateOne) SetProtocol(v catproxyproviderconfig.Protocol) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableProtocol(v *catproxyproviderconfig.Protocol) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *CatProxyProviderConfigUpdateOne) SetHost(v string) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableHost(v *string) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetBaseUsername sets the "base_username" field.
func (_u *CatProxyProviderConfigUpdateOne) SetBaseUsername(v string) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetBaseUsername(v)
	return _u
}

// SetNillableBaseUsername sets the "base_username" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableBaseUsername(v *string) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetBaseUsername(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *CatProxyProviderConfigUpdateOne) SetPassword(v string) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillablePassword(v *string) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetDefaultCountry sets the "default_country" field.
func (_u *CatProxyProviderConfigUpdateOne) SetDefaultCountry(v string) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetDefaultCountry(v)
	return _u
}

// SetNillableDefaultCountry sets the "default_country" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableDefaultCountry(v *string) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetDefaultCountry(*v)
	}
	return _u
}

// ClearDefaultCountry clears the value of the "default_country" field.
func (_u *CatProxyProviderConfigUpdateOne) ClearDefaultCountry() *CatProxyProviderConfigUpdateOne {
	_u.mutation.ClearDefaultCountry()
	return _u
}

// SetDefaultState sets the "default_state" field.
func (_u *CatProxyProviderConfigUpdateOne) SetDefaultState(v string) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetDefaultState(v)
	return _u
}

// SetNillableDefaultState sets the "default_state" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableDefaultState(v *string) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetDefaultState(*v)
	}
	return _u
}

// ClearDefaultState clears the value of the "default_state" field.
func (_u *CatProxyProviderConfigUpdateOne) ClearDefaultState() *CatProxyProviderConfigUpdateOne {
	_u.mutation.ClearDefaultState()
	return _u
}

// SetDefaultCity sets the "default_city" field.
func (_u *CatProxyProviderConfigUpdateOne) SetDefaultCity(v string) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetDefaultCity(v)
	return _u
}

// SetNillableDefaultCity sets the "default_city" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableDefaultCity(v *string) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetDefaultCity(*v)
	}
	return _u
}

// ClearDefaultCity clears the value of the "default_city" field.
func (_u *CatProxyProviderConfigUpdateOne) ClearDefaultCity() *CatProxyProviderConfigUpdateOne {
	_u.mutation.ClearDefaultCity()
	return _u
}

// SetLifetimeMinutes sets the "lifetime_minutes" field.
func (_u *CatProxyProviderConfigUpdateOne) SetLifetimeMinutes(v int) *CatProxyProviderConfigUpdateOne {
	_u.mutation.ResetLifetimeMinutes()
	_u.mutation.SetLifetimeMinutes(v)
	return _u
}

// SetNillableLifetimeMinutes sets the "lifetime_minutes" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableLifetimeMinutes(v *int) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetLifetimeMinutes(*v)
	}
	return _u
}

// AddLifetimeMinutes adds value to the "lifetime_minutes" field.
func (_u *CatProxyProviderConfigUpdateOne) AddLifetimeMinutes(v int) *CatProxyProviderConfigUpdateOne {
	_u.mutation.AddLifetimeMinutes(v)
	return _u
}

// SetStrict sets the "strict" field.
func (_u *CatProxyProviderConfigUpdateOne) SetStrict(v bool) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetStrict(v)
	return _u
}

// SetNillableStrict sets the "strict" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableStrict(v *bool) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetStrict(*v)
	}
	return _u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_u *CatProxyProviderConfigUpdateOne) SetLastProbeAt(v time.Time) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetLastProbeAt(v)
	return _u
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableLastProbeAt(v *time.Time) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetLastProbeAt(*v)
	}
	return _u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (_u *CatProxyProviderConfigUpdateOne) ClearLastProbeAt() *CatProxyProviderConfigUpdateOne {
	_u.mutation.ClearLastProbeAt()
	return _u
}

// SetLastProbeLatencyMs sets the "last_probe_latency_ms" field.
func (_u *CatProxyProviderConfigUpdateOne) SetLastProbeLatencyMs(v int) *CatProxyProviderConfigUpdateOne {
	_u.mutation.ResetLastProbeLatencyMs()
	_u.mutation.SetLastProbeLatencyMs(v)
	return _u
}

// SetNillableLastProbeLatencyMs sets the "last_probe_latency_ms" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableLastProbeLatencyMs(v *int) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetLastProbeLatencyMs(*v)
	}
	return _u
}

// AddLastProbeLatencyMs adds value to the "last_probe_latency_ms" field.
func (_u *CatProxyProviderConfigUpdateOne) AddLastProbeLatencyMs(v int) *CatProxyProviderConfigUpdateOne {
	_u.mutation.AddLastProbeLatencyMs(v)
	return _u
}

// ClearLastProbeLatencyMs clears the value of the "last_probe_latency_ms" field.
func (_u *CatProxyProviderConfigUpdateOne) ClearLastProbeLatencyMs() *CatProxyProviderConfigUpdateOne {
	_u.mutation.ClearLastProbeLatencyMs()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CatProxyProviderConfigUpdateOne) SetLastError(v string) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableLastError(v *string) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CatProxyProviderConfigUpdateOne) ClearLastError() *CatProxyProviderConfigUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastErrorAt sets the "last_error_at" field.
func (_u *CatProxyProviderConfigUpdateOne) SetLastErrorAt(v time.Time) *CatProxyProviderConfigUpdateOne {
	_u.mutation.SetLastErrorAt(v)
	return _u
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_u *CatProxyProviderConfigUpdateOne) SetNillableLastErrorAt(v *time.Time) *CatProxyProviderConfigUpdateOne {
	if v != nil {
		_u.SetLastErrorAt(*v)
	}
	return _u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (_u *CatProxyProviderConfigUpdateOne) ClearLastErrorAt() *CatProxyProviderConfigUpdateOne {
	_u.mutation.ClearLastErrorAt()
	return _u
}

// AddLeaseIDs adds the "leases" edge to the ManagedProxyLease entity by IDs.
func (_u *CatProxyProviderConfigUpdateOne) AddLeaseIDs(ids ...int64) *CatProxyProviderConfigUpdateOne {
	_u.mutation.AddLeaseIDs(ids...)
	return _u
}

// AddLeases adds the "leases" edges to the ManagedProxyLease entity.
func (_u *CatProxyProviderConfigUpdateOne) AddLeases(v ...*ManagedProxyLease) *CatProxyProviderConfigUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaseIDs(ids...)
}

// Mutation returns the CatProxyProviderConfigMutation object of the builder.
func (_u *CatProxyProviderConfigUpdateOne) Mutation() *CatProxyProviderConfigMutation {
	return _u.mutation
}

// ClearLeases clears all "leases" edges to the ManagedProxyLease entity.
func (_u *CatProxyProviderConfigUpdateOne) ClearLeases() *CatProxyProviderConfigUpdateOne {
	_u.mutation.ClearLeases()
	return _u
}

// RemoveLeaseIDs removes the "leases" edge to ManagedProxyLease entities by IDs.
func (_u *CatProxyProviderConfigUpdateOne) RemoveLeaseIDs(ids ...int64) *CatProxyProviderConfigUpdateOne {
	_u.mutation.RemoveLeaseIDs(ids...)
	return _u
}

// RemoveLeases removes "leases" edges to ManagedProxyLease entities.
func (_u *CatProxyProviderConfigUpdateOne) RemoveLeases(v ...*ManagedProxyLease) *CatProxyProviderConfigUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaseIDs(ids...)
}

// Where appends a list predicates to the CatProxyProviderConfigUpdate builder.
func (_u *CatProxyProviderConfigUpdateOne) Where(ps ...predicate.CatProxyProviderConfig) *CatProxyProviderConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CatProxyProviderConfigUpdateOne) Select(field string, fields ...string) *CatProxyProviderConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CatProxyProviderConfig entity.
func (_u *CatProxyProviderConfigUpdateOne) Save(ctx context.Context) (*CatProxyProviderConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatProxyProviderConfigUpdateOne) SaveX(ctx context.Context) *CatProxyProviderConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CatProxyProviderConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatProxyProviderConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CatProxyProviderConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := catproxyproviderconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CatProxyProviderConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := catproxyproviderconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := catproxyproviderconfig.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := catproxyproviderconfig.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := catproxyproviderconfig.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := catproxyproviderconfig.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseUsername(); ok {
		if err := catproxyproviderconfig.BaseUsernameValidator(v); err != nil {
			return &ValidationError{Name: "base_username", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.base_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := catproxyproviderconfig.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultCountry(); ok {
		if err := catproxyproviderconfig.DefaultCountryValidator(v); err != nil {
			return &ValidationError{Name: "default_country", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.default_country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultState(); ok {
		if err := catproxyproviderconfig.DefaultStateValidator(v); err != nil {
			return &ValidationError{Name: "default_state", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.default_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultCity(); ok {
		if err := catproxyproviderconfig.DefaultCityValidator(v); err != nil {
			return &ValidationError{Name: "default_city", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.default_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeMinutes(); ok {
		if err := catproxyproviderconfig.LifetimeMinutesValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_minutes", err: fmt.Errorf(`ent: validator failed for field "CatProxyProviderConfig.lifetime_minutes": %w`, err)}
		}
	}
	return nil
}

func (_u *CatProxyProviderConfigUpdateOne) sqlSave(ctx context.Context) (_node *CatProxyProviderConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(catproxyproviderconfig.Table, catproxyproviderconfig.Columns, sqlgraph.NewFieldSpec(catproxyproviderconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CatProxyProviderConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, catproxyproviderconfig.FieldID)
		for _, f := range fields {
			if !catproxyproviderconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != catproxyproviderconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(catproxyproviderconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(catproxyproviderconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(catproxyproviderconfig.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(catproxyproviderconfig.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(catproxyproviderconfig.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(catproxyproviderconfig.FieldProtocol, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(catproxyproviderconfig.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseUsername(); ok {
		_spec.SetField(catproxyproviderconfig.FieldBaseUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(catproxyproviderconfig.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultCountry(); ok {
		_spec.SetField(catproxyproviderconfig.FieldDefaultCountry, field.TypeString, value)
	}
	if _u.mutation.DefaultCountryCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldDefaultCountry, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultState(); ok {
		_spec.SetField(catproxyproviderconfig.FieldDefaultState, field.TypeString, value)
	}
	if _u.mutation.DefaultStateCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldDefaultState, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultCity(); ok {
		_spec.SetField(catproxyproviderconfig.FieldDefaultCity, field.TypeString, value)
	}
	if _u.mutation.DefaultCityCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldDefaultCity, field.TypeString)
	}
	if value, ok := _u.mutation.LifetimeMinutes(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLifetimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLifetimeMinutes(); ok {
		_spec.AddField(catproxyproviderconfig.FieldLifetimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Strict(); ok {
		_spec.SetField(catproxyproviderconfig.FieldStrict, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastProbeAt(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLastProbeAt, field.TypeTime, value)
	}
	if _u.mutation.LastProbeAtCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldLastProbeAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProbeLatencyMs(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLastProbeLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastProbeLatencyMs(); ok {
		_spec.AddField(catproxyproviderconfig.FieldLastProbeLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LastProbeLatencyMsCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldLastProbeLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorAt(); ok {
		_spec.SetField(catproxyproviderconfig.FieldLastErrorAt, field.TypeTime, value)
	}
	if _u.mutation.LastErrorAtCleared() {
		_spec.ClearField(catproxyproviderconfig.FieldLastErrorAt, field.TypeTime)
	}
	if _u.mutation.LeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   catproxyproviderconfig.LeasesTable,
			Columns: []string{catproxyproviderconfig.LeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeasesIDs(); len(nodes) > 0 && !_u.mutation.LeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   catproxyproviderconfig.LeasesTable,
			Columns: []string{catproxyproviderconfig.LeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   catproxyproviderconfig.LeasesTable,
			Columns: []string{catproxyproviderconfig.LeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CatProxyProviderConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catproxyproviderconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
