// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/catproxyproviderconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CatProxyProviderConfigDelete is the builder for deleting a CatProxyProviderConfig entity.
type CatProxyProviderConfigDelete struct {
	config
	hooks    []Hook
	mutation *CatProxyProviderConfigMutation
}

// Where appends a list predicates to the CatProxyProviderConfigDelete builder.
func (_d *CatProxyProviderConfigDelete) Where(ps ...predicate.CatProxyProviderConfig) *CatProxyProviderConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CatProxyProviderConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CatProxyProviderConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CatProxyProviderConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(catproxyproviderconfig.Table, sqlgraph.NewFieldSpec(catproxyproviderconfig.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CatProxyProviderConfigDeleteOne is the builder for deleting a single CatProxyProviderConfig entity.
type CatProxyProviderConfigDeleteOne struct {
	_d *CatProxyProviderConfigDelete
}

// Where appends a list predicates to the CatProxyProviderConfigDelete builder.
func (_d *CatProxyProviderConfigDeleteOne) Where(ps ...predicate.CatProxyProviderConfig) *CatProxyProviderConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CatProxyProviderConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{catproxyproviderconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CatProxyProviderConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
