// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/catproxyproviderconfig"
)

// CatProxyProviderConfig is the model entity for the CatProxyProviderConfig schema.
type CatProxyProviderConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ProviderType holds the value of the "provider_type" field.
	ProviderType catproxyproviderconfig.ProviderType `json:"provider_type,omitempty"`
	// Status holds the value of the "status" field.
	Status catproxyproviderconfig.Status `json:"status,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"is_default,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol catproxyproviderconfig.Protocol `json:"protocol,omitempty"`
	// Host holds the value of the "host" field.
	Host string `json:"host,omitempty"`
	// BaseUsername holds the value of the "base_username" field.
	BaseUsername string `json:"base_username,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"-"`
	// DefaultCountry holds the value of the "default_country" field.
	DefaultCountry *string `json:"default_country,omitempty"`
	// DefaultState holds the value of the "default_state" field.
	DefaultState *string `json:"default_state,omitempty"`
	// DefaultCity holds the value of the "default_city" field.
	DefaultCity *string `json:"default_city,omitempty"`
	// LifetimeMinutes holds the value of the "lifetime_minutes" field.
	LifetimeMinutes int `json:"lifetime_minutes,omitempty"`
	// Strict holds the value of the "strict" field.
	Strict bool `json:"strict,omitempty"`
	// LastProbeAt holds the value of the "last_probe_at" field.
	LastProbeAt *time.Time `json:"last_probe_at,omitempty"`
	// LastProbeLatencyMs holds the value of the "last_probe_latency_ms" field.
	LastProbeLatencyMs *int `json:"last_probe_latency_ms,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// LastErrorAt holds the value of the "last_error_at" field.
	LastErrorAt *time.Time `json:"last_error_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CatProxyProviderConfigQuery when eager-loading is set.
	Edges        CatProxyProviderConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CatProxyProviderConfigEdges holds the relations/edges for other nodes in the graph.
type CatProxyProviderConfigEdges struct {
	// Leases holds the value of the leases edge.
	Leases []*ManagedProxyLease `json:"leases,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LeasesOrErr returns the Leases value or an error if the edge
// was not loaded in eager-loading.
func (e CatProxyProviderConfigEdges) LeasesOrErr() ([]*ManagedProxyLease, error) {
	if e.loadedTypes[0] {
		return e.Leases, nil
	}
	return nil, &NotLoadedError{edge: "leases"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CatProxyProviderConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case catproxyproviderconfig.FieldIsDefault, catproxyproviderconfig.FieldStrict:
			values[i] = new(sql.NullBool)
		case catproxyproviderconfig.FieldID, catproxyproviderconfig.FieldLifetimeMinutes, catproxyproviderconfig.FieldLastProbeLatencyMs:
			values[i] = new(sql.NullInt64)
		case catproxyproviderconfig.FieldName, catproxyproviderconfig.FieldProviderType, catproxyproviderconfig.FieldStatus, catproxyproviderconfig.FieldProtocol, catproxyproviderconfig.FieldHost, catproxyproviderconfig.FieldBaseUsername, catproxyproviderconfig.FieldPassword, catproxyproviderconfig.FieldDefaultCountry, catproxyproviderconfig.FieldDefaultState, catproxyproviderconfig.FieldDefaultCity, catproxyproviderconfig.FieldLastError:
			values[i] = new(sql.NullString)
		case catproxyproviderconfig.FieldCreatedAt, catproxyproviderconfig.FieldUpdatedAt, catproxyproviderconfig.FieldLastProbeAt, catproxyproviderconfig.FieldLastErrorAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CatProxyProviderConfig fields.
func (_m *CatProxyProviderConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case catproxyproviderconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case catproxyproviderconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case catproxyproviderconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case catproxyproviderconfig.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case catproxyproviderconfig.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = catproxyproviderconfig.ProviderType(value.String)
			}
		case catproxyproviderconfig.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = catproxyproviderconfig.Status(value.String)
			}
		case catproxyproviderconfig.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case catproxyproviderconfig.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = catproxyproviderconfig.Protocol(value.String)
			}
		case catproxyproviderconfig.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case catproxyproviderconfig.FieldBaseUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_username", values[i])
			} else if value.Valid {
				_m.BaseUsername = value.String
			}
		case catproxyproviderconfig.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case catproxyproviderconfig.FieldDefaultCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_country", values[i])
			} else if value.Valid {
				_m.DefaultCountry = new(string)
				*_m.DefaultCountry = value.String
			}
		case catproxyproviderconfig.FieldDefaultState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_state", values[i])
			} else if value.Valid {
				_m.DefaultState = new(string)
				*_m.DefaultState = value.String
			}
		case catproxyproviderconfig.FieldDefaultCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_city", values[i])
			} else if value.Valid {
				_m.DefaultCity = new(string)
				*_m.DefaultCity = value.String
			}
		case catproxyproviderconfig.FieldLifetimeMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_minutes", values[i])
			} else if value.Valid {
				_m.LifetimeMinutes = int(value.Int64)
			}
		case catproxyproviderconfig.FieldStrict:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field strict", values[i])
			} else if value.Valid {
				_m.Strict = value.Bool
			}
		case catproxyproviderconfig.FieldLastProbeAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_probe_at", values[i])
			} else if value.Valid {
				_m.LastProbeAt = new(time.Time)
				*_m.LastProbeAt = value.Time
			}
		case catproxyproviderconfig.FieldLastProbeLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_probe_latency_ms", values[i])
			} else if value.Valid {
				_m.LastProbeLatencyMs = new(int)
				*_m.LastProbeLatencyMs = int(value.Int64)
			}
		case catproxyproviderconfig.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case catproxyproviderconfig.FieldLastErrorAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_at", values[i])
			} else if value.Valid {
				_m.LastErrorAt = new(time.Time)
				*_m.LastErrorAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CatProxyProviderConfig.
// This includes values selected through modifiers, order, etc.
func (_m *CatProxyProviderConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLeases queries the "leases" edge of the CatProxyProviderConfig entity.
func (_m *CatProxyProviderConfig) QueryLeases() *ManagedProxyLeaseQuery {
	return NewCatProxyProviderConfigClient(_m.config).QueryLeases(_m)
}

// Update returns a builder for updating this CatProxyProviderConfig.
// Note that you need to call CatProxyProviderConfig.Unwrap() before calling this method if this CatProxyProviderConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CatProxyProviderConfig) Update() *CatProxyProviderConfigUpdateOne {
	return NewCatProxyProviderConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CatProxyProviderConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CatProxyProviderConfig) Unwrap() *CatProxyProviderConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CatProxyProviderConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CatProxyProviderConfig) String() string {
	var builder strings.Builder
	builder.WriteString("CatProxyProviderConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocol))
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("base_username=")
	builder.WriteString(_m.BaseUsername)
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	if v := _m.DefaultCountry; v != nil {
		builder.WriteString("default_country=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DefaultState; v != nil {
		builder.WriteString("default_state=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DefaultCity; v != nil {
		builder.WriteString("default_city=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("lifetime_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.LifetimeMinutes))
	builder.WriteString(", ")
	builder.WriteString("strict=")
	builder.WriteString(fmt.Sprintf("%v", _m.Strict))
	builder.WriteString(", ")
	if v := _m.LastProbeAt; v != nil {
		builder.WriteString("last_probe_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastProbeLatencyMs; v != nil {
		builder.WriteString("last_probe_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastErrorAt; v != nil {
		builder.WriteString("last_error_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CatProxyProviderConfigs is a parsable slice of CatProxyProviderConfig.
type CatProxyProviderConfigs []*CatProxyProviderConfig
