// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/catproxyproviderconfig"
	"github.com/Wei-Shaw/sub2api/ent/managedproxylease"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// ManagedProxyLease is the model entity for the ManagedProxyLease schema.
type ManagedProxyLease struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID int64 `json:"proxy_id,omitempty"`
	// ProviderConfigID holds the value of the "provider_config_id" field.
	ProviderConfigID int64 `json:"provider_config_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// TargetCountry holds the value of the "target_country" field.
	TargetCountry *string `json:"target_country,omitempty"`
	// TargetState holds the value of the "target_state" field.
	TargetState *string `json:"target_state,omitempty"`
	// TargetCity holds the value of the "target_city" field.
	TargetCity *string `json:"target_city,omitempty"`
	// Strict holds the value of the "strict" field.
	Strict bool `json:"strict,omitempty"`
	// LifetimeMinutes holds the value of the "lifetime_minutes" field.
	LifetimeMinutes int `json:"lifetime_minutes,omitempty"`
	// State holds the value of the "state" field.
	State managedproxylease.State `json:"state,omitempty"`
	// HealthStatus holds the value of the "health_status" field.
	HealthStatus managedproxylease.HealthStatus `json:"health_status,omitempty"`
	// HealthCheckedAt holds the value of the "health_checked_at" field.
	HealthCheckedAt *time.Time `json:"health_checked_at,omitempty"`
	// ObservedExitIP holds the value of the "observed_exit_ip" field.
	ObservedExitIP *string `json:"observed_exit_ip,omitempty"`
	// ObservedCountry holds the value of the "observed_country" field.
	ObservedCountry *string `json:"observed_country,omitempty"`
	// ObservedState holds the value of the "observed_state" field.
	ObservedState *string `json:"observed_state,omitempty"`
	// ObservedCity holds the value of the "observed_city" field.
	ObservedCity *string `json:"observed_city,omitempty"`
	// ObservedLatencyMs holds the value of the "observed_latency_ms" field.
	ObservedLatencyMs *int `json:"observed_latency_ms,omitempty"`
	// ActivatedAt holds the value of the "activated_at" field.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	// LastRotatedAt holds the value of the "last_rotated_at" field.
	LastRotatedAt *time.Time `json:"last_rotated_at,omitempty"`
	// NextRotationAt holds the value of the "next_rotation_at" field.
	NextRotationAt *time.Time `json:"next_rotation_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// FailureCount holds the value of the "failure_count" field.
	FailureCount int `json:"failure_count,omitempty"`
	// ConsecutiveFailureCount holds the value of the "consecutive_failure_count" field.
	ConsecutiveFailureCount int `json:"consecutive_failure_count,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// LastErrorAt holds the value of the "last_error_at" field.
	LastErrorAt *time.Time `json:"last_error_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ManagedProxyLeaseQuery when eager-loading is set.
	Edges        ManagedProxyLeaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ManagedProxyLeaseEdges holds the relations/edges for other nodes in the graph.
type ManagedProxyLeaseEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Proxy holds the value of the proxy edge.
	Proxy *Proxy `json:"proxy,omitempty"`
	// ProviderConfig holds the value of the provider_config edge.
	ProviderConfig *CatProxyProviderConfig `json:"provider_config,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ManagedProxyLeaseEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// ProxyOrErr returns the Proxy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ManagedProxyLeaseEdges) ProxyOrErr() (*Proxy, error) {
	if e.Proxy != nil {
		return e.Proxy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "proxy"}
}

// ProviderConfigOrErr returns the ProviderConfig value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ManagedProxyLeaseEdges) ProviderConfigOrErr() (*CatProxyProviderConfig, error) {
	if e.ProviderConfig != nil {
		return e.ProviderConfig, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: catproxyproviderconfig.Label}
	}
	return nil, &NotLoadedError{edge: "provider_config"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ManagedProxyLease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case managedproxylease.FieldStrict:
			values[i] = new(sql.NullBool)
		case managedproxylease.FieldID, managedproxylease.FieldAccountID, managedproxylease.FieldProxyID, managedproxylease.FieldProviderConfigID, managedproxylease.FieldLifetimeMinutes, managedproxylease.FieldObservedLatencyMs, managedproxylease.FieldFailureCount, managedproxylease.FieldConsecutiveFailureCount:
			values[i] = new(sql.NullInt64)
		case managedproxylease.FieldSessionID, managedproxylease.FieldTargetCountry, managedproxylease.FieldTargetState, managedproxylease.FieldTargetCity, managedproxylease.FieldState, managedproxylease.FieldHealthStatus, managedproxylease.FieldObservedExitIP, managedproxylease.FieldObservedCountry, managedproxylease.FieldObservedState, managedproxylease.FieldObservedCity, managedproxylease.FieldLastError:
			values[i] = new(sql.NullString)
		case managedproxylease.FieldCreatedAt, managedproxylease.FieldUpdatedAt, managedproxylease.FieldHealthCheckedAt, managedproxylease.FieldActivatedAt, managedproxylease.FieldLastRotatedAt, managedproxylease.FieldNextRotationAt, managedproxylease.FieldExpiresAt, managedproxylease.FieldLastErrorAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ManagedProxyLease fields.
func (_m *ManagedProxyLease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case managedproxylease.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case managedproxylease.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case managedproxylease.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case managedproxylease.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case managedproxylease.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = value.Int64
			}
		case managedproxylease.FieldProviderConfigID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_config_id", values[i])
			} else if value.Valid {
				_m.ProviderConfigID = value.Int64
			}
		case managedproxylease.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case managedproxylease.FieldTargetCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_country", values[i])
			} else if value.Valid {
				_m.TargetCountry = new(string)
				*_m.TargetCountry = value.String
			}
		case managedproxylease.FieldTargetState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_state", values[i])
			} else if value.Valid {
				_m.TargetState = new(string)
				*_m.TargetState = value.String
			}
		case managedproxylease.FieldTargetCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_city", values[i])
			} else if value.Valid {
				_m.TargetCity = new(string)
				*_m.TargetCity = value.String
			}
		case managedproxylease.FieldStrict:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field strict", values[i])
			} else if value.Valid {
				_m.Strict = value.Bool
			}
		case managedproxylease.FieldLifetimeMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_minutes", values[i])
			} else if value.Valid {
				_m.LifetimeMinutes = int(value.Int64)
			}
		case managedproxylease.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = managedproxylease.State(value.String)
			}
		case managedproxylease.FieldHealthStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_status", values[i])
			} else if value.Valid {
				_m.HealthStatus = managedproxylease.HealthStatus(value.String)
			}
		case managedproxylease.FieldHealthCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field health_checked_at", values[i])
			} else if value.Valid {
				_m.HealthCheckedAt = new(time.Time)
				*_m.HealthCheckedAt = value.Time
			}
		case managedproxylease.FieldObservedExitIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field observed_exit_ip", values[i])
			} else if value.Valid {
				_m.ObservedExitIP = new(string)
				*_m.ObservedExitIP = value.String
			}
		case managedproxylease.FieldObservedCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field observed_country", values[i])
			} else if value.Valid {
				_m.ObservedCountry = new(string)
				*_m.ObservedCountry = value.String
			}
		case managedproxylease.FieldObservedState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field observed_state", values[i])
			} else if value.Valid {
				_m.ObservedState = new(string)
				*_m.ObservedState = value.String
			}
		case managedproxylease.FieldObservedCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field observed_city", values[i])
			} else if value.Valid {
				_m.ObservedCity = new(string)
				*_m.ObservedCity = value.String
			}
		case managedproxylease.FieldObservedLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field observed_latency_ms", values[i])
			} else if value.Valid {
				_m.ObservedLatencyMs = new(int)
				*_m.ObservedLatencyMs = int(value.Int64)
			}
		case managedproxylease.FieldActivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activated_at", values[i])
			} else if value.Valid {
				_m.ActivatedAt = new(time.Time)
				*_m.ActivatedAt = value.Time
			}
		case managedproxylease.FieldLastRotatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_rotated_at", values[i])
			} else if value.Valid {
				_m.LastRotatedAt = new(time.Time)
				*_m.LastRotatedAt = value.Time
			}
		case managedproxylease.FieldNextRotationAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_rotation_at", values[i])
			} else if value.Valid {
				_m.NextRotationAt = new(time.Time)
				*_m.NextRotationAt = value.Time
			}
		case managedproxylease.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case managedproxylease.FieldFailureCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failure_count", values[i])
			} else if value.Valid {
				_m.FailureCount = int(value.Int64)
			}
		case managedproxylease.FieldConsecutiveFailureCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_failure_count", values[i])
			} else if value.Valid {
				_m.ConsecutiveFailureCount = int(value.Int64)
			}
		case managedproxylease.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case managedproxylease.FieldLastErrorAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_at", values[i])
			} else if value.Valid {
				_m.LastErrorAt = new(time.Time)
				*_m.LastErrorAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ManagedProxyLease.
// This includes values selected through modifiers, order, etc.
func (_m *ManagedProxyLease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the ManagedProxyLease entity.
func (_m *ManagedProxyLease) QueryAccount() *AccountQuery {
	return NewManagedProxyLeaseClient(_m.config).QueryAccount(_m)
}

// QueryProxy queries the "proxy" edge of the ManagedProxyLease entity.
func (_m *ManagedProxyLease) QueryProxy() *ProxyQuery {
	return NewManagedProxyLeaseClient(_m.config).QueryProxy(_m)
}

// QueryProviderConfig queries the "provider_config" edge of the ManagedProxyLease entity.
func (_m *ManagedProxyLease) QueryProviderConfig() *CatProxyProviderConfigQuery {
	return NewManagedProxyLeaseClient(_m.config).QueryProviderConfig(_m)
}

// Update returns a builder for updating this ManagedProxyLease.
// Note that you need to call ManagedProxyLease.Unwrap() before calling this method if this ManagedProxyLease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ManagedProxyLease) Update() *ManagedProxyLeaseUpdateOne {
	return NewManagedProxyLeaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ManagedProxyLease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ManagedProxyLease) Unwrap() *ManagedProxyLease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ManagedProxyLease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ManagedProxyLease) String() string {
	var builder strings.Builder
	builder.WriteString("ManagedProxyLease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("proxy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProxyID))
	builder.WriteString(", ")
	builder.WriteString("provider_config_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderConfigID))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	if v := _m.TargetCountry; v != nil {
		builder.WriteString("target_country=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TargetState; v != nil {
		builder.WriteString("target_state=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TargetCity; v != nil {
		builder.WriteString("target_city=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("strict=")
	builder.WriteString(fmt.Sprintf("%v", _m.Strict))
	builder.WriteString(", ")
	builder.WriteString("lifetime_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.LifetimeMinutes))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("health_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthStatus))
	builder.WriteString(", ")
	if v := _m.HealthCheckedAt; v != nil {
		builder.WriteString("health_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ObservedExitIP; v != nil {
		builder.WriteString("observed_exit_ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ObservedCountry; v != nil {
		builder.WriteString("observed_country=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ObservedState; v != nil {
		builder.WriteString("observed_state=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ObservedCity; v != nil {
		builder.WriteString("observed_city=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ObservedLatencyMs; v != nil {
		builder.WriteString("observed_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActivatedAt; v != nil {
		builder.WriteString("activated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastRotatedAt; v != nil {
		builder.WriteString("last_rotated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextRotationAt; v != nil {
		builder.WriteString("next_rotation_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("failure_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailureCount))
	builder.WriteString(", ")
	builder.WriteString("consecutive_failure_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveFailureCount))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastErrorAt; v != nil {
		builder.WriteString("last_error_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ManagedProxyLeases is a parsable slice of ManagedProxyLease.
type ManagedProxyLeases []*ManagedProxyLease
