// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/catproxyproviderconfig"
	"github.com/Wei-Shaw/sub2api/ent/managedproxylease"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// ManagedProxyLeaseUpdate is the builder for updating ManagedProxyLease entities.
type ManagedProxyLeaseUpdate struct {
	config
	hooks    []Hook
	mutation *ManagedProxyLeaseMutation
}

// Where appends a list predicates to the ManagedProxyLeaseUpdate builder.
func (_u *ManagedProxyLeaseUpdate) Where(ps ...predicate.ManagedProxyLease) *ManagedProxyLeaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManagedProxyLeaseUpdate) SetUpdatedAt(v time.Time) *ManagedProxyLeaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ManagedProxyLeaseUpdate) SetAccountID(v int64) *ManagedProxyLeaseUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableAccountID(v *int64) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ManagedProxyLeaseUpdate) SetProxyID(v int64) *ManagedProxyLeaseUpdate {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableProxyID(v *int64) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// SetProviderConfigID sets the "provider_config_id" field.
func (_u *ManagedProxyLeaseUpdate) SetProviderConfigID(v int64) *ManagedProxyLeaseUpdate {
	_u.mutation.SetProviderConfigID(v)
	return _u
}

// SetNillableProviderConfigID sets the "provider_config_id" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableProviderConfigID(v *int64) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetProviderConfigID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ManagedProxyLeaseUpdate) SetSessionID(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableSessionID(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetTargetCountry sets the "target_country" field.
func (_u *ManagedProxyLeaseUpdate) SetTargetCountry(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetTargetCountry(v)
	return _u
}

// SetNillableTargetCountry sets the "target_country" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableTargetCountry(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetTargetCountry(*v)
	}
	return _u
}

// ClearTargetCountry clears the value of the "target_country" field.
func (_u *ManagedProxyLeaseUpdate) ClearTargetCountry() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearTargetCountry()
	return _u
}

// SetTargetState sets the "target_state" field.
func (_u *ManagedProxyLeaseUpdate) SetTargetState(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetTargetState(v)
	return _u
}

// SetNillableTargetState sets the "target_state" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableTargetState(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetTargetState(*v)
	}
	return _u
}

// ClearTargetState clears the value of the "target_state" field.
func (_u *ManagedProxyLeaseUpdate) ClearTargetState() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearTargetState()
	return _u
}

// SetTargetCity sets the "target_city" field.
func (_u *ManagedProxyLeaseUpdate) SetTargetCity(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetTargetCity(v)
	return _u
}

// SetNillableTargetCity sets the "target_city" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableTargetCity(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetTargetCity(*v)
	}
	return _u
}

// ClearTargetCity clears the value of the "target_city" field.
func (_u *ManagedProxyLeaseUpdate) ClearTargetCity() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearTargetCity()
	return _u
}

// SetStrict sets the "strict" field.
func (_u *ManagedProxyLeaseUpdate) SetStrict(v bool) *ManagedProxyLeaseUpdate {
	_u.mutation.SetStrict(v)
	return _u
}

// SetNillableStrict sets the "strict" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableStrict(v *bool) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetStrict(*v)
	}
	return _u
}

// SetLifetimeMinutes sets the "lifetime_minutes" field.
func (_u *ManagedProxyLeaseUpdate) SetLifetimeMinutes(v int) *ManagedProxyLeaseUpdate {
	_u.mutation.ResetLifetimeMinutes()
	_u.mutation.SetLifetimeMinutes(v)
	return _u
}

// SetNillableLifetimeMinutes sets the "lifetime_minutes" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableLifetimeMinutes(v *int) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetLifetimeMinutes(*v)
	}
	return _u
}

// AddLifetimeMinutes adds value to the "lifetime_minutes" field.
func (_u *ManagedProxyLeaseUpdate) AddLifetimeMinutes(v int) *ManagedProxyLeaseUpdate {
	_u.mutation.AddLifetimeMinutes(v)
	return _u
}

// SetState sets the "state" field.
func (_u *ManagedProxyLeaseUpdate) SetState(v managedproxylease.State) *ManagedProxyLeaseUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableState(v *managedproxylease.State) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetHealthStatus sets the "health_status" field.
func (_u *ManagedProxyLeaseUpdate) SetHealthStatus(v managedproxylease.HealthStatus) *ManagedProxyLeaseUpdate {
	_u.mutation.SetHealthStatus(v)
	return _u
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableHealthStatus(v *managedproxylease.HealthStatus) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetHealthStatus(*v)
	}
	return _u
}

// SetHealthCheckedAt sets the "health_checked_at" field.
func (_u *ManagedProxyLeaseUpdate) SetHealthCheckedAt(v time.Time) *ManagedProxyLeaseUpdate {
	_u.mutation.SetHealthCheckedAt(v)
	return _u
}

// SetNillableHealthCheckedAt sets the "health_checked_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableHealthCheckedAt(v *time.Time) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetHealthCheckedAt(*v)
	}
	return _u
}

// ClearHealthCheckedAt clears the value of the "health_checked_at" field.
func (_u *ManagedProxyLeaseUpdate) ClearHealthCheckedAt() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearHealthCheckedAt()
	return _u
}

// SetObservedExitIP sets the "observed_exit_ip" field.
func (_u *ManagedProxyLeaseUpdate) SetObservedExitIP(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetObservedExitIP(v)
	return _u
}

// SetNillableObservedExitIP sets the "observed_exit_ip" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableObservedExitIP(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetObservedExitIP(*v)
	}
	return _u
}

// ClearObservedExitIP clears the value of the "observed_exit_ip" field.
func (_u *ManagedProxyLeaseUpdate) ClearObservedExitIP() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearObservedExitIP()
	return _u
}

// SetObservedCountry sets the "observed_country" field.
func (_u *ManagedProxyLeaseUpdate) SetObservedCountry(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetObservedCountry(v)
	return _u
}

// SetNillableObservedCountry sets the "observed_country" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableObservedCountry(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetObservedCountry(*v)
	}
	return _u
}

// ClearObservedCountry clears the value of the "observed_country" field.
func (_u *ManagedProxyLeaseUpdate) ClearObservedCountry() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearObservedCountry()
	return _u
}

// SetObservedState sets the "observed_state" field.
func (_u *ManagedProxyLeaseUpdate) SetObservedState(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetObservedState(v)
	return _u
}

// SetNillableObservedState sets the "observed_state" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableObservedState(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetObservedState(*v)
	}
	return _u
}

// ClearObservedState clears the value of the "observed_state" field.
func (_u *ManagedProxyLeaseUpdate) ClearObservedState() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearObservedState()
	return _u
}

// SetObservedCity sets the "observed_city" field.
func (_u *ManagedProxyLeaseUpdate) SetObservedCity(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetObservedCity(v)
	return _u
}

// SetNillableObservedCity sets the "observed_city" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableObservedCity(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetObservedCity(*v)
	}
	return _u
}

// ClearObservedCity clears the value of the "observed_city" field.
func (_u *ManagedProxyLeaseUpdate) ClearObservedCity() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearObservedCity()
	return _u
}

// SetObservedLatencyMs sets the "observed_latency_ms" field.
func (_u *ManagedProxyLeaseUpdate) SetObservedLatencyMs(v int) *ManagedProxyLeaseUpdate {
	_u.mutation.ResetObservedLatencyMs()
	_u.mutation.SetObservedLatencyMs(v)
	return _u
}

// SetNillableObservedLatencyMs sets the "observed_latency_ms" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableObservedLatencyMs(v *int) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetObservedLatencyMs(*v)
	}
	return _u
}

// AddObservedLatencyMs adds value to the "observed_latency_ms" field.
func (_u *ManagedProxyLeaseUpdate) AddObservedLatencyMs(v int) *ManagedProxyLeaseUpdate {
	_u.mutation.AddObservedLatencyMs(v)
	return _u
}

// ClearObservedLatencyMs clears the value of the "observed_latency_ms" field.
func (_u *ManagedProxyLeaseUpdate) ClearObservedLatencyMs() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearObservedLatencyMs()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *ManagedProxyLeaseUpdate) SetActivatedAt(v time.Time) *ManagedProxyLeaseUpdate {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableActivatedAt(v *time.Time) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *ManagedProxyLeaseUpdate) ClearActivatedAt() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetLastRotatedAt sets the "last_rotated_at" field.
func (_u *ManagedProxyLeaseUpdate) SetLastRotatedAt(v time.Time) *ManagedProxyLeaseUpdate {
	_u.mutation.SetLastRotatedAt(v)
	return _u
}

// SetNillableLastRotatedAt sets the "last_rotated_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableLastRotatedAt(v *time.Time) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetLastRotatedAt(*v)
	}
	return _u
}

// ClearLastRotatedAt clears the value of the "last_rotated_at" field.
func (_u *ManagedProxyLeaseUpdate) ClearLastRotatedAt() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearLastRotatedAt()
	return _u
}

// SetNextRotationAt sets the "next_rotation_at" field.
func (_u *ManagedProxyLeaseUpdate) SetNextRotationAt(v time.Time) *ManagedProxyLeaseUpdate {
	_u.mutation.SetNextRotationAt(v)
	return _u
}

// SetNillableNextRotationAt sets the "next_rotation_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableNextRotationAt(v *time.Time) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetNextRotationAt(*v)
	}
	return _u
}

// ClearNextRotationAt clears the value of the "next_rotation_at" field.
func (_u *ManagedProxyLeaseUpdate) ClearNextRotationAt() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearNextRotationAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ManagedProxyLeaseUpdate) SetExpiresAt(v time.Time) *ManagedProxyLeaseUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableExpiresAt(v *time.Time) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ManagedProxyLeaseUpdate) ClearExpiresAt() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetFailureCount sets the "failure_count" field.
func (_u *ManagedProxyLeaseUpdate) SetFailureCount(v int) *ManagedProxyLeaseUpdate {
	_u.mutation.ResetFailureCount()
	_u.mutation.SetFailureCount(v)
	return _u
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableFailureCount(v *int) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetFailureCount(*v)
	}
	return _u
}

// AddFailureCount adds value to the "failure_count" field.
func (_u *ManagedProxyLeaseUpdate) AddFailureCount(v int) *ManagedProxyLeaseUpdate {
	_u.mutation.AddFailureCount(v)
	return _u
}

// SetConsecutiveFailureCount sets the "consecutive_failure_count" field.
func (_u *ManagedProxyLeaseUpdate) SetConsecutiveFailureCount(v int) *ManagedProxyLeaseUpdate {
	_u.mutation.ResetConsecutiveFailureCount()
	_u.mutation.SetConsecutiveFailureCount(v)
	return _u
}

// SetNillableConsecutiveFailureCount sets the "consecutive_failure_count" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableConsecutiveFailureCount(v *int) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetConsecutiveFailureCount(*v)
	}
	return _u
}

// AddConsecutiveFailureCount adds value to the "consecutive_failure_count" field.
func (_u *ManagedProxyLeaseUpdate) AddConsecutiveFailureCount(v int) *ManagedProxyLeaseUpdate {
	_u.mutation.AddConsecutiveFailureCount(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ManagedProxyLeaseUpdate) SetLastError(v string) *ManagedProxyLeaseUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableLastError(v *string) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ManagedProxyLeaseUpdate) ClearLastError() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastErrorAt sets the "last_error_at" field.
func (_u *ManagedProxyLeaseUpdate) SetLastErrorAt(v time.Time) *ManagedProxyLeaseUpdate {
	_u.mutation.SetLastErrorAt(v)
	return _u
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdate) SetNillableLastErrorAt(v *time.Time) *ManagedProxyLeaseUpdate {
	if v != nil {
		_u.SetLastErrorAt(*v)
	}
	return _u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (_u *ManagedProxyLeaseUpdate) ClearLastErrorAt() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearLastErrorAt()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ManagedProxyLeaseUpdate) SetAccount(v *Account) *ManagedProxyLeaseUpdate {
	return _u.SetAccountID(v.ID)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *ManagedProxyLeaseUpdate) SetProxy(v *Proxy) *ManagedProxyLeaseUpdate {
	return _u.SetProxyID(v.ID)
}

// SetProviderConfig sets the "provider_config" edge to the CatProxyProviderConfig entity.
func (_u *ManagedProxyLeaseUpdate) SetProviderConfig(v *CatProxyProviderConfig) *ManagedProxyLeaseUpdate {
	return _u.SetProviderConfigID(v.ID)
}

// Mutation returns the ManagedProxyLeaseMutation object of the builder.
func (_u *ManagedProxyLeaseUpdate) Mutation() *ManagedProxyLeaseMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ManagedProxyLeaseUpdate) ClearAccount() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *ManagedProxyLeaseUpdate) ClearProxy() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearProxy()
	return _u
}

// ClearProviderConfig clears the "provider_config" edge to the CatProxyProviderConfig entity.
func (_u *ManagedProxyLeaseUpdate) ClearProviderConfig() *ManagedProxyLeaseUpdate {
	_u.mutation.ClearProviderConfig()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ManagedProxyLeaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedProxyLeaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ManagedProxyLeaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedProxyLeaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ManagedProxyLeaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := managedproxylease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ManagedProxyLeaseUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := managedproxylease.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetCountry(); ok {
		if err := managedproxylease.TargetCountryValidator(v); err != nil {
			return &ValidationError{Name: "target_country", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetState(); ok {
		if err := managedproxylease.TargetStateValidator(v); err != nil {
			return &ValidationError{Name: "target_state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetCity(); ok {
		if err := managedproxylease.TargetCityValidator(v); err != nil {
			return &ValidationError{Name: "target_city", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeMinutes(); ok {
		if err := managedproxylease.LifetimeMinutesValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_minutes", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.lifetime_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := managedproxylease.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthStatus(); ok {
		if err := managedproxylease.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.health_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedExitIP(); ok {
		if err := managedproxylease.ObservedExitIPValidator(v); err != nil {
			return &ValidationError{Name: "observed_exit_ip", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_exit_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedCountry(); ok {
		if err := managedproxylease.ObservedCountryValidator(v); err != nil {
			return &ValidationError{Name: "observed_country", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedState(); ok {
		if err := managedproxylease.ObservedStateValidator(v); err != nil {
			return &ValidationError{Name: "observed_state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedCity(); ok {
		if err := managedproxylease.ObservedCityValidator(v); err != nil {
			return &ValidationError{Name: "observed_city", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_city": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ManagedProxyLease.account"`)
	}
	if _u.mutation.ProxyCleared() && len(_u.mutation.ProxyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ManagedProxyLease.proxy"`)
	}
	if _u.mutation.ProviderConfigCleared() && len(_u.mutation.ProviderConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ManagedProxyLease.provider_config"`)
	}
	return nil
}

func (_u *ManagedProxyLeaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(managedproxylease.Table, managedproxylease.Columns, sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(managedproxylease.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(managedproxylease.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetCountry(); ok {
		_spec.SetField(managedproxylease.FieldTargetCountry, field.TypeString, value)
	}
	if _u.mutation.TargetCountryCleared() {
		_spec.ClearField(managedproxylease.FieldTargetCountry, field.TypeString)
	}
	if value, ok := _u.mutation.TargetState(); ok {
		_spec.SetField(managedproxylease.FieldTargetState, field.TypeString, value)
	}
	if _u.mutation.TargetStateCleared() {
		_spec.ClearField(managedproxylease.FieldTargetState, field.TypeString)
	}
	if value, ok := _u.mutation.TargetCity(); ok {
		_spec.SetField(managedproxylease.FieldTargetCity, field.TypeString, value)
	}
	if _u.mutation.TargetCityCleared() {
		_spec.ClearField(managedproxylease.FieldTargetCity, field.TypeString)
	}
	if value, ok := _u.mutation.Strict(); ok {
		_spec.SetField(managedproxylease.FieldStrict, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LifetimeMinutes(); ok {
		_spec.SetField(managedproxylease.FieldLifetimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLifetimeMinutes(); ok {
		_spec.AddField(managedproxylease.FieldLifetimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(managedproxylease.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HealthStatus(); ok {
		_spec.SetField(managedproxylease.FieldHealthStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HealthCheckedAt(); ok {
		_spec.SetField(managedproxylease.FieldHealthCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.HealthCheckedAtCleared() {
		_spec.ClearField(managedproxylease.FieldHealthCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ObservedExitIP(); ok {
		_spec.SetField(managedproxylease.FieldObservedExitIP, field.TypeString, value)
	}
	if _u.mutation.ObservedExitIPCleared() {
		_spec.ClearField(managedproxylease.FieldObservedExitIP, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedCountry(); ok {
		_spec.SetField(managedproxylease.FieldObservedCountry, field.TypeString, value)
	}
	if _u.mutation.ObservedCountryCleared() {
		_spec.ClearField(managedproxylease.FieldObservedCountry, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedState(); ok {
		_spec.SetField(managedproxylease.FieldObservedState, field.TypeString, value)
	}
	if _u.mutation.ObservedStateCleared() {
		_spec.ClearField(managedproxylease.FieldObservedState, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedCity(); ok {
		_spec.SetField(managedproxylease.FieldObservedCity, field.TypeString, value)
	}
	if _u.mutation.ObservedCityCleared() {
		_spec.ClearField(managedproxylease.FieldObservedCity, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedLatencyMs(); ok {
		_spec.SetField(managedproxylease.FieldObservedLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedObservedLatencyMs(); ok {
		_spec.AddField(managedproxylease.FieldObservedLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.ObservedLatencyMsCleared() {
		_spec.ClearField(managedproxylease.FieldObservedLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(managedproxylease.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(managedproxylease.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRotatedAt(); ok {
		_spec.SetField(managedproxylease.FieldLastRotatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRotatedAtCleared() {
		_spec.ClearField(managedproxylease.FieldLastRotatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRotationAt(); ok {
		_spec.SetField(managedproxylease.FieldNextRotationAt, field.TypeTime, value)
	}
	if _u.mutation.NextRotationAtCleared() {
		_spec.ClearField(managedproxylease.FieldNextRotationAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(managedproxylease.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(managedproxylease.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureCount(); ok {
		_spec.SetField(managedproxylease.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailureCount(); ok {
		_spec.AddField(managedproxylease.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailureCount(); ok {
		_spec.SetField(managedproxylease.FieldConsecutiveFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailureCount(); ok {
		_spec.AddField(managedproxylease.FieldConsecutiveFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(managedproxylease.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(managedproxylease.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorAt(); ok {
		_spec.SetField(managedproxylease.FieldLastErrorAt, field.TypeTime, value)
	}
	if _u.mutation.LastErrorAtCleared() {
		_spec.ClearField(managedproxylease.FieldLastErrorAt, field.TypeTime)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   managedproxylease.AccountTable,
			Columns: []string{managedproxylease.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   managedproxylease.AccountTable,
			Columns: []string{managedproxylease.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProxyTable,
			Columns: []string{managedproxylease.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProxyTable,
			Columns: []string{managedproxylease.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProviderConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProviderConfigTable,
			Columns: []string{managedproxylease.ProviderConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(catproxyproviderconfig.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProviderConfigTable,
			Columns: []string{managedproxylease.ProviderConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(catproxyproviderconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedproxylease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ManagedProxyLeaseUpdateOne is the builder for updating a single ManagedProxyLease entity.
type ManagedProxyLeaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ManagedProxyLeaseMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManagedProxyLeaseUpdateOne) SetUpdatedAt(v time.Time) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ManagedProxyLeaseUpdateOne) SetAccountID(v int64) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableAccountID(v *int64) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ManagedProxyLeaseUpdateOne) SetProxyID(v int64) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableProxyID(v *int64) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// SetProviderConfigID sets the "provider_config_id" field.
func (_u *ManagedProxyLeaseUpdateOne) SetProviderConfigID(v int64) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetProviderConfigID(v)
	return _u
}

// SetNillableProviderConfigID sets the "provider_config_id" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableProviderConfigID(v *int64) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetProviderConfigID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ManagedProxyLeaseUpdateOne) SetSessionID(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableSessionID(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetTargetCountry sets the "target_country" field.
func (_u *ManagedProxyLeaseUpdateOne) SetTargetCountry(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetTargetCountry(v)
	return _u
}

// SetNillableTargetCountry sets the "target_country" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableTargetCountry(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetTargetCountry(*v)
	}
	return _u
}

// ClearTargetCountry clears the value of the "target_country" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearTargetCountry() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearTargetCountry()
	return _u
}

// SetTargetState sets the "target_state" field.
func (_u *ManagedProxyLeaseUpdateOne) SetTargetState(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetTargetState(v)
	return _u
}

// SetNillableTargetState sets the "target_state" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableTargetState(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetTargetState(*v)
	}
	return _u
}

// ClearTargetState clears the value of the "target_state" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearTargetState() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearTargetState()
	return _u
}

// SetTargetCity sets the "target_city" field.
func (_u *ManagedProxyLeaseUpdateOne) SetTargetCity(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetTargetCity(v)
	return _u
}

// SetNillableTargetCity sets the "target_city" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableTargetCity(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetTargetCity(*v)
	}
	return _u
}

// ClearTargetCity clears the value of the "target_city" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearTargetCity() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearTargetCity()
	return _u
}

// SetStrict sets the "strict" field.
func (_u *ManagedProxyLeaseUpdateOne) SetStrict(v bool) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetStrict(v)
	return _u
}

// SetNillableStrict sets the "strict" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableStrict(v *bool) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetStrict(*v)
	}
	return _u
}

// SetLifetimeMinutes sets the "lifetime_minutes" field.
func (_u *ManagedProxyLeaseUpdateOne) SetLifetimeMinutes(v int) *ManagedProxyLeaseUpdateOne {
	_u.mutation.ResetLifetimeMinutes()
	_u.mutation.SetLifetimeMinutes(v)
	return _u
}

// SetNillableLifetimeMinutes sets the "lifetime_minutes" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableLifetimeMinutes(v *int) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetLifetimeMinutes(*v)
	}
	return _u
}

// AddLifetimeMinutes adds value to the "lifetime_minutes" field.
func (_u *ManagedProxyLeaseUpdateOne) AddLifetimeMinutes(v int) *ManagedProxyLeaseUpdateOne {
	_u.mutation.AddLifetimeMinutes(v)
	return _u
}

// SetState sets the "state" field.
func (_u *ManagedProxyLeaseUpdateOne) SetState(v managedproxylease.State) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableState(v *managedproxylease.State) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetHealthStatus sets the "health_status" field.
func (_u *ManagedProxyLeaseUpdateOne) SetHealthStatus(v managedproxylease.HealthStatus) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetHealthStatus(v)
	return _u
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableHealthStatus(v *managedproxylease.HealthStatus) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetHealthStatus(*v)
	}
	return _u
}

// SetHealthCheckedAt sets the "health_checked_at" field.
func (_u *ManagedProxyLeaseUpdateOne) SetHealthCheckedAt(v time.Time) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetHealthCheckedAt(v)
	return _u
}

// SetNillableHealthCheckedAt sets the "health_checked_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableHealthCheckedAt(v *time.Time) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetHealthCheckedAt(*v)
	}
	return _u
}

// ClearHealthCheckedAt clears the value of the "health_checked_at" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearHealthCheckedAt() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearHealthCheckedAt()
	return _u
}

// SetObservedExitIP sets the "observed_exit_ip" field.
func (_u *ManagedProxyLeaseUpdateOne) SetObservedExitIP(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetObservedExitIP(v)
	return _u
}

// SetNillableObservedExitIP sets the "observed_exit_ip" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableObservedExitIP(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetObservedExitIP(*v)
	}
	return _u
}

// ClearObservedExitIP clears the value of the "observed_exit_ip" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearObservedExitIP() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearObservedExitIP()
	return _u
}

// SetObservedCountry sets the "observed_country" field.
func (_u *ManagedProxyLeaseUpdateOne) SetObservedCountry(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetObservedCountry(v)
	return _u
}

// SetNillableObservedCountry sets the "observed_country" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableObservedCountry(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetObservedCountry(*v)
	}
	return _u
}

// ClearObservedCountry clears the value of the "observed_country" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearObservedCountry() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearObservedCountry()
	return _u
}

// SetObservedState sets the "observed_state" field.
func (_u *ManagedProxyLeaseUpdateOne) SetObservedState(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetObservedState(v)
	return _u
}

// SetNillableObservedState sets the "observed_state" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableObservedState(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetObservedState(*v)
	}
	return _u
}

// ClearObservedState clears the value of the "observed_state" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearObservedState() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearObservedState()
	return _u
}

// SetObservedCity sets the "observed_city" field.
func (_u *ManagedProxyLeaseUpdateOne) SetObservedCity(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetObservedCity(v)
	return _u
}

// SetNillableObservedCity sets the "observed_city" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableObservedCity(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetObservedCity(*v)
	}
	return _u
}

// ClearObservedCity clears the value of the "observed_city" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearObservedCity() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearObservedCity()
	return _u
}

// SetObservedLatencyMs sets the "observed_latency_ms" field.
func (_u *ManagedProxyLeaseUpdateOne) SetObservedLatencyMs(v int) *ManagedProxyLeaseUpdateOne {
	_u.mutation.ResetObservedLatencyMs()
	_u.mutation.SetObservedLatencyMs(v)
	return _u
}

// SetNillableObservedLatencyMs sets the "observed_latency_ms" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableObservedLatencyMs(v *int) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetObservedLatencyMs(*v)
	}
	return _u
}

// AddObservedLatencyMs adds value to the "observed_latency_ms" field.
func (_u *ManagedProxyLeaseUpdateOne) AddObservedLatencyMs(v int) *ManagedProxyLeaseUpdateOne {
	_u.mutation.AddObservedLatencyMs(v)
	return _u
}

// ClearObservedLatencyMs clears the value of the "observed_latency_ms" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearObservedLatencyMs() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearObservedLatencyMs()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *ManagedProxyLeaseUpdateOne) SetActivatedAt(v time.Time) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableActivatedAt(v *time.Time) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearActivatedAt() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetLastRotatedAt sets the "last_rotated_at" field.
func (_u *ManagedProxyLeaseUpdateOne) SetLastRotatedAt(v time.Time) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetLastRotatedAt(v)
	return _u
}

// SetNillableLastRotatedAt sets the "last_rotated_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableLastRotatedAt(v *time.Time) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetLastRotatedAt(*v)
	}
	return _u
}

// ClearLastRotatedAt clears the value of the "last_rotated_at" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearLastRotatedAt() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearLastRotatedAt()
	return _u
}

// SetNextRotationAt sets the "next_rotation_at" field.
func (_u *ManagedProxyLeaseUpdateOne) SetNextRotationAt(v time.Time) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetNextRotationAt(v)
	return _u
}

// SetNillableNextRotationAt sets the "next_rotation_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableNextRotationAt(v *time.Time) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetNextRotationAt(*v)
	}
	return _u
}

// ClearNextRotationAt clears the value of the "next_rotation_at" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearNextRotationAt() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearNextRotationAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ManagedProxyLeaseUpdateOne) SetExpiresAt(v time.Time) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableExpiresAt(v *time.Time) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearExpiresAt() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetFailureCount sets the "failure_count" field.
func (_u *ManagedProxyLeaseUpdateOne) SetFailureCount(v int) *ManagedProxyLeaseUpdateOne {
	_u.mutation.ResetFailureCount()
	_u.mutation.SetFailureCount(v)
	return _u
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableFailureCount(v *int) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetFailureCount(*v)
	}
	return _u
}

// AddFailureCount adds value to the "failure_count" field.
func (_u *ManagedProxyLeaseUpdateOne) AddFailureCount(v int) *ManagedProxyLeaseUpdateOne {
	_u.mutation.AddFailureCount(v)
	return _u
}

// SetConsecutiveFailureCount sets the "consecutive_failure_count" field.
func (_u *ManagedProxyLeaseUpdateOne) SetConsecutiveFailureCount(v int) *ManagedProxyLeaseUpdateOne {
	_u.mutation.ResetConsecutiveFailureCount()
	_u.mutation.SetConsecutiveFailureCount(v)
	return _u
}

// SetNillableConsecutiveFailureCount sets the "consecutive_failure_count" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableConsecutiveFailureCount(v *int) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailureCount(*v)
	}
	return _u
}

// AddConsecutiveFailureCount adds value to the "consecutive_failure_count" field.
func (_u *ManagedProxyLeaseUpdateOne) AddConsecutiveFailureCount(v int) *ManagedProxyLeaseUpdateOne {
	_u.mutation.AddConsecutiveFailureCount(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ManagedProxyLeaseUpdateOne) SetLastError(v string) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableLastError(v *string) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearLastError() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastErrorAt sets the "last_error_at" field.
func (_u *ManagedProxyLeaseUpdateOne) SetLastErrorAt(v time.Time) *ManagedProxyLeaseUpdateOne {
	_u.mutation.SetLastErrorAt(v)
	return _u
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_u *ManagedProxyLeaseUpdateOne) SetNillableLastErrorAt(v *time.Time) *ManagedProxyLeaseUpdateOne {
	if v != nil {
		_u.SetLastErrorAt(*v)
	}
	return _u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (_u *ManagedProxyLeaseUpdateOne) ClearLastErrorAt() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearLastErrorAt()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ManagedProxyLeaseUpdateOne) SetAccount(v *Account) *ManagedProxyLeaseUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *ManagedProxyLeaseUpdateOne) SetProxy(v *Proxy) *ManagedProxyLeaseUpdateOne {
	return _u.SetProxyID(v.ID)
}

// SetProviderConfig sets the "provider_config" edge to the CatProxyProviderConfig entity.
func (_u *ManagedProxyLeaseUpdateOne) SetProviderConfig(v *CatProxyProviderConfig) *ManagedProxyLeaseUpdateOne {
	return _u.SetProviderConfigID(v.ID)
}

// Mutation returns the ManagedProxyLeaseMutation object of the builder.
func (_u *ManagedProxyLeaseUpdateOne) Mutation() *ManagedProxyLeaseMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ManagedProxyLeaseUpdateOne) ClearAccount() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *ManagedProxyLeaseUpdateOne) ClearProxy() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearProxy()
	return _u
}

// ClearProviderConfig clears the "provider_config" edge to the CatProxyProviderConfig entity.
func (_u *ManagedProxyLeaseUpdateOne) ClearProviderConfig() *ManagedProxyLeaseUpdateOne {
	_u.mutation.ClearProviderConfig()
	return _u
}

// Where appends a list predicates to the ManagedProxyLeaseUpdate builder.
func (_u *ManagedProxyLeaseUpdateOne) Where(ps ...predicate.ManagedProxyLease) *ManagedProxyLeaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ManagedProxyLeaseUpdateOne) Select(field string, fields ...string) *ManagedProxyLeaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ManagedProxyLease entity.
func (_u *ManagedProxyLeaseUpdateOne) Save(ctx context.Context) (*ManagedProxyLease, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedProxyLeaseUpdateOne) SaveX(ctx context.Context) *ManagedProxyLease {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ManagedProxyLeaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedProxyLeaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ManagedProxyLeaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := managedproxylease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ManagedProxyLeaseUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := managedproxylease.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetCountry(); ok {
		if err := managedproxylease.TargetCountryValidator(v); err != nil {
			return &ValidationError{Name: "target_country", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetState(); ok {
		if err := managedproxylease.TargetStateValidator(v); err != nil {
			return &ValidationError{Name: "target_state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetCity(); ok {
		if err := managedproxylease.TargetCityValidator(v); err != nil {
			return &ValidationError{Name: "target_city", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeMinutes(); ok {
		if err := managedproxylease.LifetimeMinutesValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_minutes", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.lifetime_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := managedproxylease.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthStatus(); ok {
		if err := managedproxylease.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.health_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedExitIP(); ok {
		if err := managedproxylease.ObservedExitIPValidator(v); err != nil {
			return &ValidationError{Name: "observed_exit_ip", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_exit_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedCountry(); ok {
		if err := managedproxylease.ObservedCountryValidator(v); err != nil {
			return &ValidationError{Name: "observed_country", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedState(); ok {
		if err := managedproxylease.ObservedStateValidator(v); err != nil {
			return &ValidationError{Name: "observed_state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedCity(); ok {
		if err := managedproxylease.ObservedCityValidator(v); err != nil {
			return &ValidationError{Name: "observed_city", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_city": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ManagedProxyLease.account"`)
	}
	if _u.mutation.ProxyCleared() && len(_u.mutation.ProxyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ManagedProxyLease.proxy"`)
	}
	if _u.mutation.ProviderConfigCleared() && len(_u.mutation.ProviderConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ManagedProxyLease.provider_config"`)
	}
	return nil
}

func (_u *ManagedProxyLeaseUpdateOne) sqlSave(ctx context.Context) (_node *ManagedProxyLease, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(managedproxylease.Table, managedproxylease.Columns, sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ManagedProxyLease.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, managedproxylease.FieldID)
		for _, f := range fields {
			if !managedproxylease.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != managedproxylease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(managedproxylease.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(managedproxylease.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetCountry(); ok {
		_spec.SetField(managedproxylease.FieldTargetCountry, field.TypeString, value)
	}
	if _u.mutation.TargetCountryCleared() {
		_spec.ClearField(managedproxylease.FieldTargetCountry, field.TypeString)
	}
	if value, ok := _u.mutation.TargetState(); ok {
		_spec.SetField(managedproxylease.FieldTargetState, field.TypeString, value)
	}
	if _u.mutation.TargetStateCleared() {
		_spec.ClearField(managedproxylease.FieldTargetState, field.TypeString)
	}
	if value, ok := _u.mutation.TargetCity(); ok {
		_spec.SetField(managedproxylease.FieldTargetCity, field.TypeString, value)
	}
	if _u.mutation.TargetCityCleared() {
		_spec.ClearField(managedproxylease.FieldTargetCity, field.TypeString)
	}
	if value, ok := _u.mutation.Strict(); ok {
		_spec.SetField(managedproxylease.FieldStrict, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LifetimeMinutes(); ok {
		_spec.SetField(managedproxylease.FieldLifetimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLifetimeMinutes(); ok {
		_spec.AddField(managedproxylease.FieldLifetimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(managedproxylease.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HealthStatus(); ok {
		_spec.SetField(managedproxylease.FieldHealthStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HealthCheckedAt(); ok {
		_spec.SetField(managedproxylease.FieldHealthCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.HealthCheckedAtCleared() {
		_spec.ClearField(managedproxylease.FieldHealthCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ObservedExitIP(); ok {
		_spec.SetField(managedproxylease.FieldObservedExitIP, field.TypeString, value)
	}
	if _u.mutation.ObservedExitIPCleared() {
		_spec.ClearField(managedproxylease.FieldObservedExitIP, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedCountry(); ok {
		_spec.SetField(managedproxylease.FieldObservedCountry, field.TypeString, value)
	}
	if _u.mutation.ObservedCountryCleared() {
		_spec.ClearField(managedproxylease.FieldObservedCountry, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedState(); ok {
		_spec.SetField(managedproxylease.FieldObservedState, field.TypeString, value)
	}
	if _u.mutation.ObservedStateCleared() {
		_spec.ClearField(managedproxylease.FieldObservedState, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedCity(); ok {
		_spec.SetField(managedproxylease.FieldObservedCity, field.TypeString, value)
	}
	if _u.mutation.ObservedCityCleared() {
		_spec.ClearField(managedproxylease.FieldObservedCity, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedLatencyMs(); ok {
		_spec.SetField(managedproxylease.FieldObservedLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedObservedLatencyMs(); ok {
		_spec.AddField(managedproxylease.FieldObservedLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.ObservedLatencyMsCleared() {
		_spec.ClearField(managedproxylease.FieldObservedLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(managedproxylease.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(managedproxylease.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRotatedAt(); ok {
		_spec.SetField(managedproxylease.FieldLastRotatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRotatedAtCleared() {
		_spec.ClearField(managedproxylease.FieldLastRotatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRotationAt(); ok {
		_spec.SetField(managedproxylease.FieldNextRotationAt, field.TypeTime, value)
	}
	if _u.mutation.NextRotationAtCleared() {
		_spec.ClearField(managedproxylease.FieldNextRotationAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(managedproxylease.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(managedproxylease.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureCount(); ok {
		_spec.SetField(managedproxylease.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailureCount(); ok {
		_spec.AddField(managedproxylease.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailureCount(); ok {
		_spec.SetField(managedproxylease.FieldConsecutiveFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailureCount(); ok {
		_spec.AddField(managedproxylease.FieldConsecutiveFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(managedproxylease.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(managedproxylease.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorAt(); ok {
		_spec.SetField(managedproxylease.FieldLastErrorAt, field.TypeTime, value)
	}
	if _u.mutation.LastErrorAtCleared() {
		_spec.ClearField(managedproxylease.FieldLastErrorAt, field.TypeTime)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   managedproxylease.AccountTable,
			Columns: []string{managedproxylease.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   managedproxylease.AccountTable,
			Columns: []string{managedproxylease.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProxyTable,
			Columns: []string{managedproxylease.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProxyTable,
			Columns: []string{managedproxylease.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProviderConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProviderConfigTable,
			Columns: []string{managedproxylease.ProviderConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(catproxyproviderconfig.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProviderConfigTable,
			Columns: []string{managedproxylease.ProviderConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(catproxyproviderconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ManagedProxyLease{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedproxylease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
