// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/catproxyproviderconfig"
	"github.com/Wei-Shaw/sub2api/ent/managedproxylease"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// ManagedProxyLeaseCreate is the builder for creating a ManagedProxyLease entity.
type ManagedProxyLeaseCreate struct {
	config
	mutation *ManagedProxyLeaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ManagedProxyLeaseCreate) SetCreatedAt(v time.Time) *ManagedProxyLeaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableCreatedAt(v *time.Time) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ManagedProxyLeaseCreate) SetUpdatedAt(v time.Time) *ManagedProxyLeaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableUpdatedAt(v *time.Time) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ManagedProxyLeaseCreate) SetAccountID(v int64) *ManagedProxyLeaseCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *ManagedProxyLeaseCreate) SetProxyID(v int64) *ManagedProxyLeaseCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetProviderConfigID sets the "provider_config_id" field.
func (_c *ManagedProxyLeaseCreate) SetProviderConfigID(v int64) *ManagedProxyLeaseCreate {
	_c.mutation.SetProviderConfigID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *ManagedProxyLeaseCreate) SetSessionID(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetTargetCountry sets the "target_country" field.
func (_c *ManagedProxyLeaseCreate) SetTargetCountry(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetTargetCountry(v)
	return _c
}

// SetNillableTargetCountry sets the "target_country" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableTargetCountry(v *string) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetTargetCountry(*v)
	}
	return _c
}

// SetTargetState sets the "target_state" field.
func (_c *ManagedProxyLeaseCreate) SetTargetState(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetTargetState(v)
	return _c
}

// SetNillableTargetState sets the "target_state" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableTargetState(v *string) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetTargetState(*v)
	}
	return _c
}

// SetTargetCity sets the "target_city" field.
func (_c *ManagedProxyLeaseCreate) SetTargetCity(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetTargetCity(v)
	return _c
}

// SetNillableTargetCity sets the "target_city" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableTargetCity(v *string) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetTargetCity(*v)
	}
	return _c
}

// SetStrict sets the "strict" field.
func (_c *ManagedProxyLeaseCreate) SetStrict(v bool) *ManagedProxyLeaseCreate {
	_c.mutation.SetStrict(v)
	return _c
}

// SetLifetimeMinutes sets the "lifetime_minutes" field.
func (_c *ManagedProxyLeaseCreate) SetLifetimeMinutes(v int) *ManagedProxyLeaseCreate {
	_c.mutation.SetLifetimeMinutes(v)
	return _c
}

// SetState sets the "state" field.
func (_c *ManagedProxyLeaseCreate) SetState(v managedproxylease.State) *ManagedProxyLeaseCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableState(v *managedproxylease.State) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetHealthStatus sets the "health_status" field.
func (_c *ManagedProxyLeaseCreate) SetHealthStatus(v managedproxylease.HealthStatus) *ManagedProxyLeaseCreate {
	_c.mutation.SetHealthStatus(v)
	return _c
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableHealthStatus(v *managedproxylease.HealthStatus) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetHealthStatus(*v)
	}
	return _c
}

// SetHealthCheckedAt sets the "health_checked_at" field.
func (_c *ManagedProxyLeaseCreate) SetHealthCheckedAt(v time.Time) *ManagedProxyLeaseCreate {
	_c.mutation.SetHealthCheckedAt(v)
	return _c
}

// SetNillableHealthCheckedAt sets the "health_checked_at" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableHealthCheckedAt(v *time.Time) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetHealthCheckedAt(*v)
	}
	return _c
}

// SetObservedExitIP sets the "observed_exit_ip" field.
func (_c *ManagedProxyLeaseCreate) SetObservedExitIP(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetObservedExitIP(v)
	return _c
}

// SetNillableObservedExitIP sets the "observed_exit_ip" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableObservedExitIP(v *string) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetObservedExitIP(*v)
	}
	return _c
}

// SetObservedCountry sets the "observed_country" field.
func (_c *ManagedProxyLeaseCreate) SetObservedCountry(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetObservedCountry(v)
	return _c
}

// SetNillableObservedCountry sets the "observed_country" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableObservedCountry(v *string) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetObservedCountry(*v)
	}
	return _c
}

// SetObservedState sets the "observed_state" field.
func (_c *ManagedProxyLeaseCreate) SetObservedState(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetObservedState(v)
	return _c
}

// SetNillableObservedState sets the "observed_state" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableObservedState(v *string) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetObservedState(*v)
	}
	return _c
}

// SetObservedCity sets the "observed_city" field.
func (_c *ManagedProxyLeaseCreate) SetObservedCity(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetObservedCity(v)
	return _c
}

// SetNillableObservedCity sets the "observed_city" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableObservedCity(v *string) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetObservedCity(*v)
	}
	return _c
}

// SetObservedLatencyMs sets the "observed_latency_ms" field.
func (_c *ManagedProxyLeaseCreate) SetObservedLatencyMs(v int) *ManagedProxyLeaseCreate {
	_c.mutation.SetObservedLatencyMs(v)
	return _c
}

// SetNillableObservedLatencyMs sets the "observed_latency_ms" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableObservedLatencyMs(v *int) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetObservedLatencyMs(*v)
	}
	return _c
}

// SetActivatedAt sets the "activated_at" field.
func (_c *ManagedProxyLeaseCreate) SetActivatedAt(v time.Time) *ManagedProxyLeaseCreate {
	_c.mutation.SetActivatedAt(v)
	return _c
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableActivatedAt(v *time.Time) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetActivatedAt(*v)
	}
	return _c
}

// SetLastRotatedAt sets the "last_rotated_at" field.
func (_c *ManagedProxyLeaseCreate) SetLastRotatedAt(v time.Time) *ManagedProxyLeaseCreate {
	_c.mutation.SetLastRotatedAt(v)
	return _c
}

// SetNillableLastRotatedAt sets the "last_rotated_at" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableLastRotatedAt(v *time.Time) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetLastRotatedAt(*v)
	}
	return _c
}

// SetNextRotationAt sets the "next_rotation_at" field.
func (_c *ManagedProxyLeaseCreate) SetNextRotationAt(v time.Time) *ManagedProxyLeaseCreate {
	_c.mutation.SetNextRotationAt(v)
	return _c
}

// SetNillableNextRotationAt sets the "next_rotation_at" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableNextRotationAt(v *time.Time) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetNextRotationAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ManagedProxyLeaseCreate) SetExpiresAt(v time.Time) *ManagedProxyLeaseCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableExpiresAt(v *time.Time) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *ManagedProxyLeaseCreate) SetFailureCount(v int) *ManagedProxyLeaseCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableFailureCount(v *int) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetFailureCount(*v)
	}
	return _c
}

// SetConsecutiveFailureCount sets the "consecutive_failure_count" field.
func (_c *ManagedProxyLeaseCreate) SetConsecutiveFailureCount(v int) *ManagedProxyLeaseCreate {
	_c.mutation.SetConsecutiveFailureCount(v)
	return _c
}

// SetNillableConsecutiveFailureCount sets the "consecutive_failure_count" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableConsecutiveFailureCount(v *int) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetConsecutiveFailureCount(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ManagedProxyLeaseCreate) SetLastError(v string) *ManagedProxyLeaseCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableLastError(v *string) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetLastErrorAt sets the "last_error_at" field.
func (_c *ManagedProxyLeaseCreate) SetLastErrorAt(v time.Time) *ManagedProxyLeaseCreate {
	_c.mutation.SetLastErrorAt(v)
	return _c
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_c *ManagedProxyLeaseCreate) SetNillableLastErrorAt(v *time.Time) *ManagedProxyLeaseCreate {
	if v != nil {
		_c.SetLastErrorAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *ManagedProxyLeaseCreate) SetAccount(v *Account) *ManagedProxyLeaseCreate {
	return _c.SetAccountID(v.ID)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *ManagedProxyLeaseCreate) SetProxy(v *Proxy) *ManagedProxyLeaseCreate {
	return _c.SetProxyID(v.ID)
}

// SetProviderConfig sets the "provider_config" edge to the CatProxyProviderConfig entity.
func (_c *ManagedProxyLeaseCreate) SetProviderConfig(v *CatProxyProviderConfig) *ManagedProxyLeaseCreate {
	return _c.SetProviderConfigID(v.ID)
}

// Mutation returns the ManagedProxyLeaseMutation object of the builder.
func (_c *ManagedProxyLeaseCreate) Mutation() *ManagedProxyLeaseMutation {
	return _c.mutation
}

// Save creates the ManagedProxyLease in the database.
func (_c *ManagedProxyLeaseCreate) Save(ctx context.Context) (*ManagedProxyLease, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ManagedProxyLeaseCreate) SaveX(ctx context.Context) *ManagedProxyLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ManagedProxyLeaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ManagedProxyLeaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ManagedProxyLeaseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := managedproxylease.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := managedproxylease.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := managedproxylease.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.HealthStatus(); !ok {
		v := managedproxylease.DefaultHealthStatus
		_c.mutation.SetHealthStatus(v)
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		v := managedproxylease.DefaultFailureCount
		_c.mutation.SetFailureCount(v)
	}
	if _, ok := _c.mutation.ConsecutiveFailureCount(); !ok {
		v := managedproxylease.DefaultConsecutiveFailureCount
		_c.mutation.SetConsecutiveFailureCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ManagedProxyLeaseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ManagedProxyLease.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ManagedProxyLease.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ManagedProxyLease.account_id"`)}
	}
	if _, ok := _c.mutation.ProxyID(); !ok {
		return &ValidationError{Name: "proxy_id", err: errors.New(`ent: missing required field "ManagedProxyLease.proxy_id"`)}
	}
	if _, ok := _c.mutation.ProviderConfigID(); !ok {
		return &ValidationError{Name: "provider_config_id", err: errors.New(`ent: missing required field "ManagedProxyLease.provider_config_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "ManagedProxyLease.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := managedproxylease.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.session_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TargetCountry(); ok {
		if err := managedproxylease.TargetCountryValidator(v); err != nil {
			return &ValidationError{Name: "target_country", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_country": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TargetState(); ok {
		if err := managedproxylease.TargetStateValidator(v); err != nil {
			return &ValidationError{Name: "target_state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_state": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TargetCity(); ok {
		if err := managedproxylease.TargetCityValidator(v); err != nil {
			return &ValidationError{Name: "target_city", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.target_city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Strict(); !ok {
		return &ValidationError{Name: "strict", err: errors.New(`ent: missing required field "ManagedProxyLease.strict"`)}
	}
	if _, ok := _c.mutation.LifetimeMinutes(); !ok {
		return &ValidationError{Name: "lifetime_minutes", err: errors.New(`ent: missing required field "ManagedProxyLease.lifetime_minutes"`)}
	}
	if v, ok := _c.mutation.LifetimeMinutes(); ok {
		if err := managedproxylease.LifetimeMinutesValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_minutes", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.lifetime_minutes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "ManagedProxyLease.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := managedproxylease.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HealthStatus(); !ok {
		return &ValidationError{Name: "health_status", err: errors.New(`ent: missing required field "ManagedProxyLease.health_status"`)}
	}
	if v, ok := _c.mutation.HealthStatus(); ok {
		if err := managedproxylease.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.health_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ObservedExitIP(); ok {
		if err := managedproxylease.ObservedExitIPValidator(v); err != nil {
			return &ValidationError{Name: "observed_exit_ip", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_exit_ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ObservedCountry(); ok {
		if err := managedproxylease.ObservedCountryValidator(v); err != nil {
			return &ValidationError{Name: "observed_country", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_country": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ObservedState(); ok {
		if err := managedproxylease.ObservedStateValidator(v); err != nil {
			return &ValidationError{Name: "observed_state", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_state": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ObservedCity(); ok {
		if err := managedproxylease.ObservedCityValidator(v); err != nil {
			return &ValidationError{Name: "observed_city", err: fmt.Errorf(`ent: validator failed for field "ManagedProxyLease.observed_city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "ManagedProxyLease.failure_count"`)}
	}
	if _, ok := _c.mutation.ConsecutiveFailureCount(); !ok {
		return &ValidationError{Name: "consecutive_failure_count", err: errors.New(`ent: missing required field "ManagedProxyLease.consecutive_failure_count"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "ManagedProxyLease.account"`)}
	}
	if len(_c.mutation.ProxyIDs()) == 0 {
		return &ValidationError{Name: "proxy", err: errors.New(`ent: missing required edge "ManagedProxyLease.proxy"`)}
	}
	if len(_c.mutation.ProviderConfigIDs()) == 0 {
		return &ValidationError{Name: "provider_config", err: errors.New(`ent: missing required edge "ManagedProxyLease.provider_config"`)}
	}
	return nil
}

func (_c *ManagedProxyLeaseCreate) sqlSave(ctx context.Context) (*ManagedProxyLease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ManagedProxyLeaseCreate) createSpec() (*ManagedProxyLease, *sqlgraph.CreateSpec) {
	var (
		_node = &ManagedProxyLease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(managedproxylease.Table, sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(managedproxylease.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(managedproxylease.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(managedproxylease.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.TargetCountry(); ok {
		_spec.SetField(managedproxylease.FieldTargetCountry, field.TypeString, value)
		_node.TargetCountry = &value
	}
	if value, ok := _c.mutation.TargetState(); ok {
		_spec.SetField(managedproxylease.FieldTargetState, field.TypeString, value)
		_node.TargetState = &value
	}
	if value, ok := _c.mutation.TargetCity(); ok {
		_spec.SetField(managedproxylease.FieldTargetCity, field.TypeString, value)
		_node.TargetCity = &value
	}
	if value, ok := _c.mutation.Strict(); ok {
		_spec.SetField(managedproxylease.FieldStrict, field.TypeBool, value)
		_node.Strict = value
	}
	if value, ok := _c.mutation.LifetimeMinutes(); ok {
		_spec.SetField(managedproxylease.FieldLifetimeMinutes, field.TypeInt, value)
		_node.LifetimeMinutes = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(managedproxylease.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.HealthStatus(); ok {
		_spec.SetField(managedproxylease.FieldHealthStatus, field.TypeEnum, value)
		_node.HealthStatus = value
	}
	if value, ok := _c.mutation.HealthCheckedAt(); ok {
		_spec.SetField(managedproxylease.FieldHealthCheckedAt, field.TypeTime, value)
		_node.HealthCheckedAt = &value
	}
	if value, ok := _c.mutation.ObservedExitIP(); ok {
		_spec.SetField(managedproxylease.FieldObservedExitIP, field.TypeString, value)
		_node.ObservedExitIP = &value
	}
	if value, ok := _c.mutation.ObservedCountry(); ok {
		_spec.SetField(managedproxylease.FieldObservedCountry, field.TypeString, value)
		_node.ObservedCountry = &value
	}
	if value, ok := _c.mutation.ObservedState(); ok {
		_spec.SetField(managedproxylease.FieldObservedState, field.TypeString, value)
		_node.ObservedState = &value
	}
	if value, ok := _c.mutation.ObservedCity(); ok {
		_spec.SetField(managedproxylease.FieldObservedCity, field.TypeString, value)
		_node.ObservedCity = &value
	}
	if value, ok := _c.mutation.ObservedLatencyMs(); ok {
		_spec.SetField(managedproxylease.FieldObservedLatencyMs, field.TypeInt, value)
		_node.ObservedLatencyMs = &value
	}
	if value, ok := _c.mutation.ActivatedAt(); ok {
		_spec.SetField(managedproxylease.FieldActivatedAt, field.TypeTime, value)
		_node.ActivatedAt = &value
	}
	if value, ok := _c.mutation.LastRotatedAt(); ok {
		_spec.SetField(managedproxylease.FieldLastRotatedAt, field.TypeTime, value)
		_node.LastRotatedAt = &value
	}
	if value, ok := _c.mutation.NextRotationAt(); ok {
		_spec.SetField(managedproxylease.FieldNextRotationAt, field.TypeTime, value)
		_node.NextRotationAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(managedproxylease.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(managedproxylease.FieldFailureCount, field.TypeInt, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.ConsecutiveFailureCount(); ok {
		_spec.SetField(managedproxylease.FieldConsecutiveFailureCount, field.TypeInt, value)
		_node.ConsecutiveFailureCount = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(managedproxylease.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.LastErrorAt(); ok {
		_spec.SetField(managedproxylease.FieldLastErrorAt, field.TypeTime, value)
		_node.LastErrorAt = &value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   managedproxylease.AccountTable,
			Columns: []string{managedproxylease.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProxyTable,
			Columns: []string{managedproxylease.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProxyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProviderConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedproxylease.ProviderConfigTable,
			Columns: []string{managedproxylease.ProviderConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(catproxyproviderconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderConfigID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ManagedProxyLease.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ManagedProxyLeaseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ManagedProxyLeaseCreate) OnConflict(opts ...sql.ConflictOption) *ManagedProxyLeaseUpsertOne {
	_c.conflict = opts
	return &ManagedProxyLeaseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ManagedProxyLease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ManagedProxyLeaseCreate) OnConflictColumns(columns ...string) *ManagedProxyLeaseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ManagedProxyLeaseUpsertOne{
		create: _c,
	}
}

type (
	// ManagedProxyLeaseUpsertOne is the builder for "upsert"-ing
	//  one ManagedProxyLease node.
	ManagedProxyLeaseUpsertOne struct {
		create *ManagedProxyLeaseCreate
	}

	// ManagedProxyLeaseUpsert is the "OnConflict" setter.
	ManagedProxyLeaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ManagedProxyLeaseUpsert) SetUpdatedAt(v time.Time) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateUpdatedAt() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ManagedProxyLeaseUpsert) SetAccountID(v int64) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateAccountID() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldAccountID)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *ManagedProxyLeaseUpsert) SetProxyID(v int64) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateProxyID() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldProxyID)
	return u
}

// SetProviderConfigID sets the "provider_config_id" field.
func (u *ManagedProxyLeaseUpsert) SetProviderConfigID(v int64) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldProviderConfigID, v)
	return u
}

// UpdateProviderConfigID sets the "provider_config_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateProviderConfigID() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldProviderConfigID)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *ManagedProxyLeaseUpsert) SetSessionID(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateSessionID() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldSessionID)
	return u
}

// SetTargetCountry sets the "target_country" field.
func (u *ManagedProxyLeaseUpsert) SetTargetCountry(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldTargetCountry, v)
	return u
}

// UpdateTargetCountry sets the "target_country" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateTargetCountry() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldTargetCountry)
	return u
}

// ClearTargetCountry clears the value of the "target_country" field.
func (u *ManagedProxyLeaseUpsert) ClearTargetCountry() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldTargetCountry)
	return u
}

// SetTargetState sets the "target_state" field.
func (u *ManagedProxyLeaseUpsert) SetTargetState(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldTargetState, v)
	return u
}

// UpdateTargetState sets the "target_state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateTargetState() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldTargetState)
	return u
}

// ClearTargetState clears the value of the "target_state" field.
func (u *ManagedProxyLeaseUpsert) ClearTargetState() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldTargetState)
	return u
}

// SetTargetCity sets the "target_city" field.
func (u *ManagedProxyLeaseUpsert) SetTargetCity(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldTargetCity, v)
	return u
}

// UpdateTargetCity sets the "target_city" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateTargetCity() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldTargetCity)
	return u
}

// ClearTargetCity clears the value of the "target_city" field.
func (u *ManagedProxyLeaseUpsert) ClearTargetCity() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldTargetCity)
	return u
}

// SetStrict sets the "strict" field.
func (u *ManagedProxyLeaseUpsert) SetStrict(v bool) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldStrict, v)
	return u
}

// UpdateStrict sets the "strict" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateStrict() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldStrict)
	return u
}

// SetLifetimeMinutes sets the "lifetime_minutes" field.
func (u *ManagedProxyLeaseUpsert) SetLifetimeMinutes(v int) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldLifetimeMinutes, v)
	return u
}

// UpdateLifetimeMinutes sets the "lifetime_minutes" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateLifetimeMinutes() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldLifetimeMinutes)
	return u
}

// AddLifetimeMinutes adds v to the "lifetime_minutes" field.
func (u *ManagedProxyLeaseUpsert) AddLifetimeMinutes(v int) *ManagedProxyLeaseUpsert {
	u.Add(managedproxylease.FieldLifetimeMinutes, v)
	return u
}

// SetState sets the "state" field.
func (u *ManagedProxyLeaseUpsert) SetState(v managedproxylease.State) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateState() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldState)
	return u
}

// SetHealthStatus sets the "health_status" field.
func (u *ManagedProxyLeaseUpsert) SetHealthStatus(v managedproxylease.HealthStatus) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldHealthStatus, v)
	return u
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateHealthStatus() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldHealthStatus)
	return u
}

// SetHealthCheckedAt sets the "health_checked_at" field.
func (u *ManagedProxyLeaseUpsert) SetHealthCheckedAt(v time.Time) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldHealthCheckedAt, v)
	return u
}

// UpdateHealthCheckedAt sets the "health_checked_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateHealthCheckedAt() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldHealthCheckedAt)
	return u
}

// ClearHealthCheckedAt clears the value of the "health_checked_at" field.
func (u *ManagedProxyLeaseUpsert) ClearHealthCheckedAt() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldHealthCheckedAt)
	return u
}

// SetObservedExitIP sets the "observed_exit_ip" field.
func (u *ManagedProxyLeaseUpsert) SetObservedExitIP(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldObservedExitIP, v)
	return u
}

// UpdateObservedExitIP sets the "observed_exit_ip" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateObservedExitIP() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldObservedExitIP)
	return u
}

// ClearObservedExitIP clears the value of the "observed_exit_ip" field.
func (u *ManagedProxyLeaseUpsert) ClearObservedExitIP() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldObservedExitIP)
	return u
}

// SetObservedCountry sets the "observed_country" field.
func (u *ManagedProxyLeaseUpsert) SetObservedCountry(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldObservedCountry, v)
	return u
}

// UpdateObservedCountry sets the "observed_country" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateObservedCountry() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldObservedCountry)
	return u
}

// ClearObservedCountry clears the value of the "observed_country" field.
func (u *ManagedProxyLeaseUpsert) ClearObservedCountry() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldObservedCountry)
	return u
}

// SetObservedState sets the "observed_state" field.
func (u *ManagedProxyLeaseUpsert) SetObservedState(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldObservedState, v)
	return u
}

// UpdateObservedState sets the "observed_state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateObservedState() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldObservedState)
	return u
}

// ClearObservedState clears the value of the "observed_state" field.
func (u *ManagedProxyLeaseUpsert) ClearObservedState() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldObservedState)
	return u
}

// SetObservedCity sets the "observed_city" field.
func (u *ManagedProxyLeaseUpsert) SetObservedCity(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldObservedCity, v)
	return u
}

// UpdateObservedCity sets the "observed_city" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateObservedCity() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldObservedCity)
	return u
}

// ClearObservedCity clears the value of the "observed_city" field.
func (u *ManagedProxyLeaseUpsert) ClearObservedCity() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldObservedCity)
	return u
}

// SetObservedLatencyMs sets the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsert) SetObservedLatencyMs(v int) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldObservedLatencyMs, v)
	return u
}

// UpdateObservedLatencyMs sets the "observed_latency_ms" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateObservedLatencyMs() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldObservedLatencyMs)
	return u
}

// AddObservedLatencyMs adds v to the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsert) AddObservedLatencyMs(v int) *ManagedProxyLeaseUpsert {
	u.Add(managedproxylease.FieldObservedLatencyMs, v)
	return u
}

// ClearObservedLatencyMs clears the value of the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsert) ClearObservedLatencyMs() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldObservedLatencyMs)
	return u
}

// SetActivatedAt sets the "activated_at" field.
func (u *ManagedProxyLeaseUpsert) SetActivatedAt(v time.Time) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldActivatedAt, v)
	return u
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateActivatedAt() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldActivatedAt)
	return u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *ManagedProxyLeaseUpsert) ClearActivatedAt() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldActivatedAt)
	return u
}

// SetLastRotatedAt sets the "last_rotated_at" field.
func (u *ManagedProxyLeaseUpsert) SetLastRotatedAt(v time.Time) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldLastRotatedAt, v)
	return u
}

// UpdateLastRotatedAt sets the "last_rotated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateLastRotatedAt() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldLastRotatedAt)
	return u
}

// ClearLastRotatedAt clears the value of the "last_rotated_at" field.
func (u *ManagedProxyLeaseUpsert) ClearLastRotatedAt() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldLastRotatedAt)
	return u
}

// SetNextRotationAt sets the "next_rotation_at" field.
func (u *ManagedProxyLeaseUpsert) SetNextRotationAt(v time.Time) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldNextRotationAt, v)
	return u
}

// UpdateNextRotationAt sets the "next_rotation_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateNextRotationAt() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldNextRotationAt)
	return u
}

// ClearNextRotationAt clears the value of the "next_rotation_at" field.
func (u *ManagedProxyLeaseUpsert) ClearNextRotationAt() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldNextRotationAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ManagedProxyLeaseUpsert) SetExpiresAt(v time.Time) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateExpiresAt() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ManagedProxyLeaseUpsert) ClearExpiresAt() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldExpiresAt)
	return u
}

// SetFailureCount sets the "failure_count" field.
func (u *ManagedProxyLeaseUpsert) SetFailureCount(v int) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldFailureCount, v)
	return u
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateFailureCount() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldFailureCount)
	return u
}

// AddFailureCount adds v to the "failure_count" field.
func (u *ManagedProxyLeaseUpsert) AddFailureCount(v int) *ManagedProxyLeaseUpsert {
	u.Add(managedproxylease.FieldFailureCount, v)
	return u
}

// SetConsecutiveFailureCount sets the "consecutive_failure_count" field.
func (u *ManagedProxyLeaseUpsert) SetConsecutiveFailureCount(v int) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldConsecutiveFailureCount, v)
	return u
}

// UpdateConsecutiveFailureCount sets the "consecutive_failure_count" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateConsecutiveFailureCount() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldConsecutiveFailureCount)
	return u
}

// AddConsecutiveFailureCount adds v to the "consecutive_failure_count" field.
func (u *ManagedProxyLeaseUpsert) AddConsecutiveFailureCount(v int) *ManagedProxyLeaseUpsert {
	u.Add(managedproxylease.FieldConsecutiveFailureCount, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *ManagedProxyLeaseUpsert) SetLastError(v string) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateLastError() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *ManagedProxyLeaseUpsert) ClearLastError() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldLastError)
	return u
}

// SetLastErrorAt sets the "last_error_at" field.
func (u *ManagedProxyLeaseUpsert) SetLastErrorAt(v time.Time) *ManagedProxyLeaseUpsert {
	u.Set(managedproxylease.FieldLastErrorAt, v)
	return u
}

// UpdateLastErrorAt sets the "last_error_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsert) UpdateLastErrorAt() *ManagedProxyLeaseUpsert {
	u.SetExcluded(managedproxylease.FieldLastErrorAt)
	return u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (u *ManagedProxyLeaseUpsert) ClearLastErrorAt() *ManagedProxyLeaseUpsert {
	u.SetNull(managedproxylease.FieldLastErrorAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ManagedProxyLease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ManagedProxyLeaseUpsertOne) UpdateNewValues() *ManagedProxyLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(managedproxylease.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ManagedProxyLease.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ManagedProxyLeaseUpsertOne) Ignore() *ManagedProxyLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ManagedProxyLeaseUpsertOne) DoNothing() *ManagedProxyLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ManagedProxyLeaseCreate.OnConflict
// documentation for more info.
func (u *ManagedProxyLeaseUpsertOne) Update(set func(*ManagedProxyLeaseUpsert)) *ManagedProxyLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ManagedProxyLeaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ManagedProxyLeaseUpsertOne) SetUpdatedAt(v time.Time) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateUpdatedAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ManagedProxyLeaseUpsertOne) SetAccountID(v int64) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateAccountID() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateAccountID()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *ManagedProxyLeaseUpsertOne) SetProxyID(v int64) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateProxyID() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateProxyID()
	})
}

// SetProviderConfigID sets the "provider_config_id" field.
func (u *ManagedProxyLeaseUpsertOne) SetProviderConfigID(v int64) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetProviderConfigID(v)
	})
}

// UpdateProviderConfigID sets the "provider_config_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateProviderConfigID() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateProviderConfigID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *ManagedProxyLeaseUpsertOne) SetSessionID(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateSessionID() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateSessionID()
	})
}

// SetTargetCountry sets the "target_country" field.
func (u *ManagedProxyLeaseUpsertOne) SetTargetCountry(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetTargetCountry(v)
	})
}

// UpdateTargetCountry sets the "target_country" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateTargetCountry() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateTargetCountry()
	})
}

// ClearTargetCountry clears the value of the "target_country" field.
func (u *ManagedProxyLeaseUpsertOne) ClearTargetCountry() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearTargetCountry()
	})
}

// SetTargetState sets the "target_state" field.
func (u *ManagedProxyLeaseUpsertOne) SetTargetState(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetTargetState(v)
	})
}

// UpdateTargetState sets the "target_state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateTargetState() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateTargetState()
	})
}

// ClearTargetState clears the value of the "target_state" field.
func (u *ManagedProxyLeaseUpsertOne) ClearTargetState() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearTargetState()
	})
}

// SetTargetCity sets the "target_city" field.
func (u *ManagedProxyLeaseUpsertOne) SetTargetCity(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetTargetCity(v)
	})
}

// UpdateTargetCity sets the "target_city" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateTargetCity() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateTargetCity()
	})
}

// ClearTargetCity clears the value of the "target_city" field.
func (u *ManagedProxyLeaseUpsertOne) ClearTargetCity() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearTargetCity()
	})
}

// SetStrict sets the "strict" field.
func (u *ManagedProxyLeaseUpsertOne) SetStrict(v bool) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetStrict(v)
	})
}

// UpdateStrict sets the "strict" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateStrict() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateStrict()
	})
}

// SetLifetimeMinutes sets the "lifetime_minutes" field.
func (u *ManagedProxyLeaseUpsertOne) SetLifetimeMinutes(v int) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetLifetimeMinutes(v)
	})
}

// AddLifetimeMinutes adds v to the "lifetime_minutes" field.
func (u *ManagedProxyLeaseUpsertOne) AddLifetimeMinutes(v int) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.AddLifetimeMinutes(v)
	})
}

// UpdateLifetimeMinutes sets the "lifetime_minutes" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateLifetimeMinutes() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateLifetimeMinutes()
	})
}

// SetState sets the "state" field.
func (u *ManagedProxyLeaseUpsertOne) SetState(v managedproxylease.State) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateState() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateState()
	})
}

// SetHealthStatus sets the "health_status" field.
func (u *ManagedProxyLeaseUpsertOne) SetHealthStatus(v managedproxylease.HealthStatus) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetHealthStatus(v)
	})
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateHealthStatus() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateHealthStatus()
	})
}

// SetHealthCheckedAt sets the "health_checked_at" field.
func (u *ManagedProxyLeaseUpsertOne) SetHealthCheckedAt(v time.Time) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetHealthCheckedAt(v)
	})
}

// UpdateHealthCheckedAt sets the "health_checked_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateHealthCheckedAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateHealthCheckedAt()
	})
}

// ClearHealthCheckedAt clears the value of the "health_checked_at" field.
func (u *ManagedProxyLeaseUpsertOne) ClearHealthCheckedAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearHealthCheckedAt()
	})
}

// SetObservedExitIP sets the "observed_exit_ip" field.
func (u *ManagedProxyLeaseUpsertOne) SetObservedExitIP(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedExitIP(v)
	})
}

// UpdateObservedExitIP sets the "observed_exit_ip" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateObservedExitIP() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedExitIP()
	})
}

// ClearObservedExitIP clears the value of the "observed_exit_ip" field.
func (u *ManagedProxyLeaseUpsertOne) ClearObservedExitIP() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedExitIP()
	})
}

// SetObservedCountry sets the "observed_country" field.
func (u *ManagedProxyLeaseUpsertOne) SetObservedCountry(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedCountry(v)
	})
}

// UpdateObservedCountry sets the "observed_country" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateObservedCountry() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedCountry()
	})
}

// ClearObservedCountry clears the value of the "observed_country" field.
func (u *ManagedProxyLeaseUpsertOne) ClearObservedCountry() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedCountry()
	})
}

// SetObservedState sets the "observed_state" field.
func (u *ManagedProxyLeaseUpsertOne) SetObservedState(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedState(v)
	})
}

// UpdateObservedState sets the "observed_state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateObservedState() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedState()
	})
}

// ClearObservedState clears the value of the "observed_state" field.
func (u *ManagedProxyLeaseUpsertOne) ClearObservedState() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedState()
	})
}

// SetObservedCity sets the "observed_city" field.
func (u *ManagedProxyLeaseUpsertOne) SetObservedCity(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedCity(v)
	})
}

// UpdateObservedCity sets the "observed_city" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateObservedCity() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedCity()
	})
}

// ClearObservedCity clears the value of the "observed_city" field.
func (u *ManagedProxyLeaseUpsertOne) ClearObservedCity() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedCity()
	})
}

// SetObservedLatencyMs sets the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsertOne) SetObservedLatencyMs(v int) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedLatencyMs(v)
	})
}

// AddObservedLatencyMs adds v to the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsertOne) AddObservedLatencyMs(v int) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.AddObservedLatencyMs(v)
	})
}

// UpdateObservedLatencyMs sets the "observed_latency_ms" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateObservedLatencyMs() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedLatencyMs()
	})
}

// ClearObservedLatencyMs clears the value of the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsertOne) ClearObservedLatencyMs() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedLatencyMs()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *ManagedProxyLeaseUpsertOne) SetActivatedAt(v time.Time) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateActivatedAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateActivatedAt()
	})
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *ManagedProxyLeaseUpsertOne) ClearActivatedAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearActivatedAt()
	})
}

// SetLastRotatedAt sets the "last_rotated_at" field.
func (u *ManagedProxyLeaseUpsertOne) SetLastRotatedAt(v time.Time) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetLastRotatedAt(v)
	})
}

// UpdateLastRotatedAt sets the "last_rotated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateLastRotatedAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateLastRotatedAt()
	})
}

// ClearLastRotatedAt clears the value of the "last_rotated_at" field.
func (u *ManagedProxyLeaseUpsertOne) ClearLastRotatedAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearLastRotatedAt()
	})
}

// SetNextRotationAt sets the "next_rotation_at" field.
func (u *ManagedProxyLeaseUpsertOne) SetNextRotationAt(v time.Time) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetNextRotationAt(v)
	})
}

// UpdateNextRotationAt sets the "next_rotation_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateNextRotationAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateNextRotationAt()
	})
}

// ClearNextRotationAt clears the value of the "next_rotation_at" field.
func (u *ManagedProxyLeaseUpsertOne) ClearNextRotationAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearNextRotationAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ManagedProxyLeaseUpsertOne) SetExpiresAt(v time.Time) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateExpiresAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ManagedProxyLeaseUpsertOne) ClearExpiresAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearExpiresAt()
	})
}

// SetFailureCount sets the "failure_count" field.
func (u *ManagedProxyLeaseUpsertOne) SetFailureCount(v int) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetFailureCount(v)
	})
}

// AddFailureCount adds v to the "failure_count" field.
func (u *ManagedProxyLeaseUpsertOne) AddFailureCount(v int) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.AddFailureCount(v)
	})
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateFailureCount() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateFailureCount()
	})
}

// SetConsecutiveFailureCount sets the "consecutive_failure_count" field.
func (u *ManagedProxyLeaseUpsertOne) SetConsecutiveFailureCount(v int) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetConsecutiveFailureCount(v)
	})
}

// AddConsecutiveFailureCount adds v to the "consecutive_failure_count" field.
func (u *ManagedProxyLeaseUpsertOne) AddConsecutiveFailureCount(v int) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.AddConsecutiveFailureCount(v)
	})
}

// UpdateConsecutiveFailureCount sets the "consecutive_failure_count" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateConsecutiveFailureCount() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateConsecutiveFailureCount()
	})
}

// SetLastError sets the "last_error" field.
func (u *ManagedProxyLeaseUpsertOne) SetLastError(v string) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateLastError() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ManagedProxyLeaseUpsertOne) ClearLastError() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearLastError()
	})
}

// SetLastErrorAt sets the "last_error_at" field.
func (u *ManagedProxyLeaseUpsertOne) SetLastErrorAt(v time.Time) *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetLastErrorAt(v)
	})
}

// UpdateLastErrorAt sets the "last_error_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertOne) UpdateLastErrorAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateLastErrorAt()
	})
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (u *ManagedProxyLeaseUpsertOne) ClearLastErrorAt() *ManagedProxyLeaseUpsertOne {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearLastErrorAt()
	})
}

// Exec executes the query.
func (u *ManagedProxyLeaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ManagedProxyLeaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ManagedProxyLeaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ManagedProxyLeaseUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ManagedProxyLeaseUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ManagedProxyLeaseCreateBulk is the builder for creating many ManagedProxyLease entities in bulk.
type ManagedProxyLeaseCreateBulk struct {
	config
	err      error
	builders []*ManagedProxyLeaseCreate
	conflict []sql.ConflictOption
}

// Save creates the ManagedProxyLease entities in the database.
func (_c *ManagedProxyLeaseCreateBulk) Save(ctx context.Context) ([]*ManagedProxyLease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ManagedProxyLease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ManagedProxyLeaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ManagedProxyLeaseCreateBulk) SaveX(ctx context.Context) []*ManagedProxyLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ManagedProxyLeaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ManagedProxyLeaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ManagedProxyLease.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ManagedProxyLeaseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ManagedProxyLeaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *ManagedProxyLeaseUpsertBulk {
	_c.conflict = opts
	return &ManagedProxyLeaseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ManagedProxyLease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ManagedProxyLeaseCreateBulk) OnConflictColumns(columns ...string) *ManagedProxyLeaseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ManagedProxyLeaseUpsertBulk{
		create: _c,
	}
}

// ManagedProxyLeaseUpsertBulk is the builder for "upsert"-ing
// a bulk of ManagedProxyLease nodes.
type ManagedProxyLeaseUpsertBulk struct {
	create *ManagedProxyLeaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ManagedProxyLease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ManagedProxyLeaseUpsertBulk) UpdateNewValues() *ManagedProxyLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(managedproxylease.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ManagedProxyLease.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ManagedProxyLeaseUpsertBulk) Ignore() *ManagedProxyLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ManagedProxyLeaseUpsertBulk) DoNothing() *ManagedProxyLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ManagedProxyLeaseCreateBulk.OnConflict
// documentation for more info.
func (u *ManagedProxyLeaseUpsertBulk) Update(set func(*ManagedProxyLeaseUpsert)) *ManagedProxyLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ManagedProxyLeaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ManagedProxyLeaseUpsertBulk) SetUpdatedAt(v time.Time) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateUpdatedAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ManagedProxyLeaseUpsertBulk) SetAccountID(v int64) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateAccountID() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateAccountID()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *ManagedProxyLeaseUpsertBulk) SetProxyID(v int64) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateProxyID() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateProxyID()
	})
}

// SetProviderConfigID sets the "provider_config_id" field.
func (u *ManagedProxyLeaseUpsertBulk) SetProviderConfigID(v int64) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetProviderConfigID(v)
	})
}

// UpdateProviderConfigID sets the "provider_config_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateProviderConfigID() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateProviderConfigID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *ManagedProxyLeaseUpsertBulk) SetSessionID(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateSessionID() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateSessionID()
	})
}

// SetTargetCountry sets the "target_country" field.
func (u *ManagedProxyLeaseUpsertBulk) SetTargetCountry(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetTargetCountry(v)
	})
}

// UpdateTargetCountry sets the "target_country" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateTargetCountry() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateTargetCountry()
	})
}

// ClearTargetCountry clears the value of the "target_country" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearTargetCountry() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearTargetCountry()
	})
}

// SetTargetState sets the "target_state" field.
func (u *ManagedProxyLeaseUpsertBulk) SetTargetState(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetTargetState(v)
	})
}

// UpdateTargetState sets the "target_state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateTargetState() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateTargetState()
	})
}

// ClearTargetState clears the value of the "target_state" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearTargetState() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearTargetState()
	})
}

// SetTargetCity sets the "target_city" field.
func (u *ManagedProxyLeaseUpsertBulk) SetTargetCity(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetTargetCity(v)
	})
}

// UpdateTargetCity sets the "target_city" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateTargetCity() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateTargetCity()
	})
}

// ClearTargetCity clears the value of the "target_city" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearTargetCity() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearTargetCity()
	})
}

// SetStrict sets the "strict" field.
func (u *ManagedProxyLeaseUpsertBulk) SetStrict(v bool) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetStrict(v)
	})
}

// UpdateStrict sets the "strict" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateStrict() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateStrict()
	})
}

// SetLifetimeMinutes sets the "lifetime_minutes" field.
func (u *ManagedProxyLeaseUpsertBulk) SetLifetimeMinutes(v int) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetLifetimeMinutes(v)
	})
}

// AddLifetimeMinutes adds v to the "lifetime_minutes" field.
func (u *ManagedProxyLeaseUpsertBulk) AddLifetimeMinutes(v int) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.AddLifetimeMinutes(v)
	})
}

// UpdateLifetimeMinutes sets the "lifetime_minutes" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateLifetimeMinutes() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateLifetimeMinutes()
	})
}

// SetState sets the "state" field.
func (u *ManagedProxyLeaseUpsertBulk) SetState(v managedproxylease.State) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateState() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateState()
	})
}

// SetHealthStatus sets the "health_status" field.
func (u *ManagedProxyLeaseUpsertBulk) SetHealthStatus(v managedproxylease.HealthStatus) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetHealthStatus(v)
	})
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateHealthStatus() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateHealthStatus()
	})
}

// SetHealthCheckedAt sets the "health_checked_at" field.
func (u *ManagedProxyLeaseUpsertBulk) SetHealthCheckedAt(v time.Time) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetHealthCheckedAt(v)
	})
}

// UpdateHealthCheckedAt sets the "health_checked_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateHealthCheckedAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateHealthCheckedAt()
	})
}

// ClearHealthCheckedAt clears the value of the "health_checked_at" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearHealthCheckedAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearHealthCheckedAt()
	})
}

// SetObservedExitIP sets the "observed_exit_ip" field.
func (u *ManagedProxyLeaseUpsertBulk) SetObservedExitIP(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedExitIP(v)
	})
}

// UpdateObservedExitIP sets the "observed_exit_ip" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateObservedExitIP() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedExitIP()
	})
}

// ClearObservedExitIP clears the value of the "observed_exit_ip" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearObservedExitIP() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedExitIP()
	})
}

// SetObservedCountry sets the "observed_country" field.
func (u *ManagedProxyLeaseUpsertBulk) SetObservedCountry(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedCountry(v)
	})
}

// UpdateObservedCountry sets the "observed_country" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateObservedCountry() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedCountry()
	})
}

// ClearObservedCountry clears the value of the "observed_country" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearObservedCountry() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedCountry()
	})
}

// SetObservedState sets the "observed_state" field.
func (u *ManagedProxyLeaseUpsertBulk) SetObservedState(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedState(v)
	})
}

// UpdateObservedState sets the "observed_state" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateObservedState() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedState()
	})
}

// ClearObservedState clears the value of the "observed_state" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearObservedState() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedState()
	})
}

// SetObservedCity sets the "observed_city" field.
func (u *ManagedProxyLeaseUpsertBulk) SetObservedCity(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedCity(v)
	})
}

// UpdateObservedCity sets the "observed_city" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateObservedCity() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedCity()
	})
}

// ClearObservedCity clears the value of the "observed_city" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearObservedCity() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedCity()
	})
}

// SetObservedLatencyMs sets the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsertBulk) SetObservedLatencyMs(v int) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetObservedLatencyMs(v)
	})
}

// AddObservedLatencyMs adds v to the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsertBulk) AddObservedLatencyMs(v int) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.AddObservedLatencyMs(v)
	})
}

// UpdateObservedLatencyMs sets the "observed_latency_ms" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateObservedLatencyMs() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateObservedLatencyMs()
	})
}

// ClearObservedLatencyMs clears the value of the "observed_latency_ms" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearObservedLatencyMs() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearObservedLatencyMs()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *ManagedProxyLeaseUpsertBulk) SetActivatedAt(v time.Time) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateActivatedAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateActivatedAt()
	})
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearActivatedAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearActivatedAt()
	})
}

// SetLastRotatedAt sets the "last_rotated_at" field.
func (u *ManagedProxyLeaseUpsertBulk) SetLastRotatedAt(v time.Time) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetLastRotatedAt(v)
	})
}

// UpdateLastRotatedAt sets the "last_rotated_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateLastRotatedAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateLastRotatedAt()
	})
}

// ClearLastRotatedAt clears the value of the "last_rotated_at" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearLastRotatedAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearLastRotatedAt()
	})
}

// SetNextRotationAt sets the "next_rotation_at" field.
func (u *ManagedProxyLeaseUpsertBulk) SetNextRotationAt(v time.Time) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetNextRotationAt(v)
	})
}

// UpdateNextRotationAt sets the "next_rotation_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateNextRotationAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateNextRotationAt()
	})
}

// ClearNextRotationAt clears the value of the "next_rotation_at" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearNextRotationAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearNextRotationAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ManagedProxyLeaseUpsertBulk) SetExpiresAt(v time.Time) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateExpiresAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearExpiresAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearExpiresAt()
	})
}

// SetFailureCount sets the "failure_count" field.
func (u *ManagedProxyLeaseUpsertBulk) SetFailureCount(v int) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetFailureCount(v)
	})
}

// AddFailureCount adds v to the "failure_count" field.
func (u *ManagedProxyLeaseUpsertBulk) AddFailureCount(v int) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.AddFailureCount(v)
	})
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateFailureCount() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateFailureCount()
	})
}

// SetConsecutiveFailureCount sets the "consecutive_failure_count" field.
func (u *ManagedProxyLeaseUpsertBulk) SetConsecutiveFailureCount(v int) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetConsecutiveFailureCount(v)
	})
}

// AddConsecutiveFailureCount adds v to the "consecutive_failure_count" field.
func (u *ManagedProxyLeaseUpsertBulk) AddConsecutiveFailureCount(v int) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.AddConsecutiveFailureCount(v)
	})
}

// UpdateConsecutiveFailureCount sets the "consecutive_failure_count" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateConsecutiveFailureCount() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateConsecutiveFailureCount()
	})
}

// SetLastError sets the "last_error" field.
func (u *ManagedProxyLeaseUpsertBulk) SetLastError(v string) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateLastError() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearLastError() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearLastError()
	})
}

// SetLastErrorAt sets the "last_error_at" field.
func (u *ManagedProxyLeaseUpsertBulk) SetLastErrorAt(v time.Time) *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.SetLastErrorAt(v)
	})
}

// UpdateLastErrorAt sets the "last_error_at" field to the value that was provided on create.
func (u *ManagedProxyLeaseUpsertBulk) UpdateLastErrorAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.UpdateLastErrorAt()
	})
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (u *ManagedProxyLeaseUpsertBulk) ClearLastErrorAt() *ManagedProxyLeaseUpsertBulk {
	return u.Update(func(s *ManagedProxyLeaseUpsert) {
		s.ClearLastErrorAt()
	})
}

// Exec executes the query.
func (u *ManagedProxyLeaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ManagedProxyLeaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ManagedProxyLeaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ManagedProxyLeaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
