// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/managedproxylease"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ManagedProxyLeaseDelete is the builder for deleting a ManagedProxyLease entity.
type ManagedProxyLeaseDelete struct {
	config
	hooks    []Hook
	mutation *ManagedProxyLeaseMutation
}

// Where appends a list predicates to the ManagedProxyLeaseDelete builder.
func (_d *ManagedProxyLeaseDelete) Where(ps ...predicate.ManagedProxyLease) *ManagedProxyLeaseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ManagedProxyLeaseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ManagedProxyLeaseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ManagedProxyLeaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(managedproxylease.Table, sqlgraph.NewFieldSpec(managedproxylease.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ManagedProxyLeaseDeleteOne is the builder for deleting a single ManagedProxyLease entity.
type ManagedProxyLeaseDeleteOne struct {
	_d *ManagedProxyLeaseDelete
}

// Where appends a list predicates to the ManagedProxyLeaseDelete builder.
func (_d *ManagedProxyLeaseDeleteOne) Where(ps ...predicate.ManagedProxyLease) *ManagedProxyLeaseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ManagedProxyLeaseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{managedproxylease.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ManagedProxyLeaseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
