// Code generated by ent, DO NOT EDIT.

package catproxyproviderconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldName, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldIsDefault, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldHost, v))
}

// BaseUsername applies equality check predicate on the "base_username" field. It's identical to BaseUsernameEQ.
func BaseUsername(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldBaseUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldPassword, v))
}

// DefaultCountry applies equality check predicate on the "default_country" field. It's identical to DefaultCountryEQ.
func DefaultCountry(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldDefaultCountry, v))
}

// DefaultState applies equality check predicate on the "default_state" field. It's identical to DefaultStateEQ.
func DefaultState(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldDefaultState, v))
}

// DefaultCity applies equality check predicate on the "default_city" field. It's identical to DefaultCityEQ.
func DefaultCity(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldDefaultCity, v))
}

// LifetimeMinutes applies equality check predicate on the "lifetime_minutes" field. It's identical to LifetimeMinutesEQ.
func LifetimeMinutes(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLifetimeMinutes, v))
}

// Strict applies equality check predicate on the "strict" field. It's identical to StrictEQ.
func Strict(v bool) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldStrict, v))
}

// LastProbeAt applies equality check predicate on the "last_probe_at" field. It's identical to LastProbeAtEQ.
func LastProbeAt(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastProbeLatencyMs applies equality check predicate on the "last_probe_latency_ms" field. It's identical to LastProbeLatencyMsEQ.
func LastProbeLatencyMs(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLastProbeLatencyMs, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLastError, v))
}

// LastErrorAt applies equality check predicate on the "last_error_at" field. It's identical to LastErrorAtEQ.
func LastErrorAt(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLastErrorAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContainsFold(FieldName, v))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v ProviderType) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldProviderType, v))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v ProviderType) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldProviderType, v))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...ProviderType) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldProviderType, vs...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...ProviderType) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldProviderType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldStatus, vs...))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldIsDefault, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v Protocol) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v Protocol) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...Protocol) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...Protocol) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldProtocol, vs...))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContainsFold(FieldHost, v))
}

// BaseUsernameEQ applies the EQ predicate on the "base_username" field.
func BaseUsernameEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldBaseUsername, v))
}

// BaseUsernameNEQ applies the NEQ predicate on the "base_username" field.
func BaseUsernameNEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldBaseUsername, v))
}

// BaseUsernameIn applies the In predicate on the "base_username" field.
func BaseUsernameIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldBaseUsername, vs...))
}

// BaseUsernameNotIn applies the NotIn predicate on the "base_username" field.
func BaseUsernameNotIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldBaseUsername, vs...))
}

// BaseUsernameGT applies the GT predicate on the "base_username" field.
func BaseUsernameGT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldBaseUsername, v))
}

// BaseUsernameGTE applies the GTE predicate on the "base_username" field.
func BaseUsernameGTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldBaseUsername, v))
}

// BaseUsernameLT applies the LT predicate on the "base_username" field.
func BaseUsernameLT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldBaseUsername, v))
}

// BaseUsernameLTE applies the LTE predicate on the "base_username" field.
func BaseUsernameLTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldBaseUsername, v))
}

// BaseUsernameContains applies the Contains predicate on the "base_username" field.
func BaseUsernameContains(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContains(FieldBaseUsername, v))
}

// BaseUsernameHasPrefix applies the HasPrefix predicate on the "base_username" field.
func BaseUsernameHasPrefix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasPrefix(FieldBaseUsername, v))
}

// BaseUsernameHasSuffix applies the HasSuffix predicate on the "base_username" field.
func BaseUsernameHasSuffix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasSuffix(FieldBaseUsername, v))
}

// BaseUsernameEqualFold applies the EqualFold predicate on the "base_username" field.
func BaseUsernameEqualFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEqualFold(FieldBaseUsername, v))
}

// BaseUsernameContainsFold applies the ContainsFold predicate on the "base_username" field.
func BaseUsernameContainsFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContainsFold(FieldBaseUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContainsFold(FieldPassword, v))
}

// DefaultCountryEQ applies the EQ predicate on the "default_country" field.
func DefaultCountryEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldDefaultCountry, v))
}

// DefaultCountryNEQ applies the NEQ predicate on the "default_country" field.
func DefaultCountryNEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldDefaultCountry, v))
}

// DefaultCountryIn applies the In predicate on the "default_country" field.
func DefaultCountryIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldDefaultCountry, vs...))
}

// DefaultCountryNotIn applies the NotIn predicate on the "default_country" field.
func DefaultCountryNotIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldDefaultCountry, vs...))
}

// DefaultCountryGT applies the GT predicate on the "default_country" field.
func DefaultCountryGT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldDefaultCountry, v))
}

// DefaultCountryGTE applies the GTE predicate on the "default_country" field.
func DefaultCountryGTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldDefaultCountry, v))
}

// DefaultCountryLT applies the LT predicate on the "default_country" field.
func DefaultCountryLT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldDefaultCountry, v))
}

// DefaultCountryLTE applies the LTE predicate on the "default_country" field.
func DefaultCountryLTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldDefaultCountry, v))
}

// DefaultCountryContains applies the Contains predicate on the "default_country" field.
func DefaultCountryContains(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContains(FieldDefaultCountry, v))
}

// DefaultCountryHasPrefix applies the HasPrefix predicate on the "default_country" field.
func DefaultCountryHasPrefix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasPrefix(FieldDefaultCountry, v))
}

// DefaultCountryHasSuffix applies the HasSuffix predicate on the "default_country" field.
func DefaultCountryHasSuffix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasSuffix(FieldDefaultCountry, v))
}

// DefaultCountryIsNil applies the IsNil predicate on the "default_country" field.
func DefaultCountryIsNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIsNull(FieldDefaultCountry))
}

// DefaultCountryNotNil applies the NotNil predicate on the "default_country" field.
func DefaultCountryNotNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotNull(FieldDefaultCountry))
}

// DefaultCountryEqualFold applies the EqualFold predicate on the "default_country" field.
func DefaultCountryEqualFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEqualFold(FieldDefaultCountry, v))
}

// DefaultCountryContainsFold applies the ContainsFold predicate on the "default_country" field.
func DefaultCountryContainsFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContainsFold(FieldDefaultCountry, v))
}

// DefaultStateEQ applies the EQ predicate on the "default_state" field.
func DefaultStateEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldDefaultState, v))
}

// DefaultStateNEQ applies the NEQ predicate on the "default_state" field.
func DefaultStateNEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldDefaultState, v))
}

// DefaultStateIn applies the In predicate on the "default_state" field.
func DefaultStateIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldDefaultState, vs...))
}

// DefaultStateNotIn applies the NotIn predicate on the "default_state" field.
func DefaultStateNotIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldDefaultState, vs...))
}

// DefaultStateGT applies the GT predicate on the "default_state" field.
func DefaultStateGT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldDefaultState, v))
}

// DefaultStateGTE applies the GTE predicate on the "default_state" field.
func DefaultStateGTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldDefaultState, v))
}

// DefaultStateLT applies the LT predicate on the "default_state" field.
func DefaultStateLT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldDefaultState, v))
}

// DefaultStateLTE applies the LTE predicate on the "default_state" field.
func DefaultStateLTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldDefaultState, v))
}

// DefaultStateContains applies the Contains predicate on the "default_state" field.
func DefaultStateContains(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContains(FieldDefaultState, v))
}

// DefaultStateHasPrefix applies the HasPrefix predicate on the "default_state" field.
func DefaultStateHasPrefix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasPrefix(FieldDefaultState, v))
}

// DefaultStateHasSuffix applies the HasSuffix predicate on the "default_state" field.
func DefaultStateHasSuffix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasSuffix(FieldDefaultState, v))
}

// DefaultStateIsNil applies the IsNil predicate on the "default_state" field.
func DefaultStateIsNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIsNull(FieldDefaultState))
}

// DefaultStateNotNil applies the NotNil predicate on the "default_state" field.
func DefaultStateNotNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotNull(FieldDefaultState))
}

// DefaultStateEqualFold applies the EqualFold predicate on the "default_state" field.
func DefaultStateEqualFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEqualFold(FieldDefaultState, v))
}

// DefaultStateContainsFold applies the ContainsFold predicate on the "default_state" field.
func DefaultStateContainsFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContainsFold(FieldDefaultState, v))
}

// DefaultCityEQ applies the EQ predicate on the "default_city" field.
func DefaultCityEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldDefaultCity, v))
}

// DefaultCityNEQ applies the NEQ predicate on the "default_city" field.
func DefaultCityNEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldDefaultCity, v))
}

// DefaultCityIn applies the In predicate on the "default_city" field.
func DefaultCityIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldDefaultCity, vs...))
}

// DefaultCityNotIn applies the NotIn predicate on the "default_city" field.
func DefaultCityNotIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldDefaultCity, vs...))
}

// DefaultCityGT applies the GT predicate on the "default_city" field.
func DefaultCityGT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldDefaultCity, v))
}

// DefaultCityGTE applies the GTE predicate on the "default_city" field.
func DefaultCityGTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldDefaultCity, v))
}

// DefaultCityLT applies the LT predicate on the "default_city" field.
func DefaultCityLT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldDefaultCity, v))
}

// DefaultCityLTE applies the LTE predicate on the "default_city" field.
func DefaultCityLTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldDefaultCity, v))
}

// DefaultCityContains applies the Contains predicate on the "default_city" field.
func DefaultCityContains(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContains(FieldDefaultCity, v))
}

// DefaultCityHasPrefix applies the HasPrefix predicate on the "default_city" field.
func DefaultCityHasPrefix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasPrefix(FieldDefaultCity, v))
}

// DefaultCityHasSuffix applies the HasSuffix predicate on the "default_city" field.
func DefaultCityHasSuffix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasSuffix(FieldDefaultCity, v))
}

// DefaultCityIsNil applies the IsNil predicate on the "default_city" field.
func DefaultCityIsNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIsNull(FieldDefaultCity))
}

// DefaultCityNotNil applies the NotNil predicate on the "default_city" field.
func DefaultCityNotNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotNull(FieldDefaultCity))
}

// DefaultCityEqualFold applies the EqualFold predicate on the "default_city" field.
func DefaultCityEqualFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEqualFold(FieldDefaultCity, v))
}

// DefaultCityContainsFold applies the ContainsFold predicate on the "default_city" field.
func DefaultCityContainsFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContainsFold(FieldDefaultCity, v))
}

// LifetimeMinutesEQ applies the EQ predicate on the "lifetime_minutes" field.
func LifetimeMinutesEQ(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLifetimeMinutes, v))
}

// LifetimeMinutesNEQ applies the NEQ predicate on the "lifetime_minutes" field.
func LifetimeMinutesNEQ(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldLifetimeMinutes, v))
}

// LifetimeMinutesIn applies the In predicate on the "lifetime_minutes" field.
func LifetimeMinutesIn(vs ...int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldLifetimeMinutes, vs...))
}

// LifetimeMinutesNotIn applies the NotIn predicate on the "lifetime_minutes" field.
func LifetimeMinutesNotIn(vs ...int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldLifetimeMinutes, vs...))
}

// LifetimeMinutesGT applies the GT predicate on the "lifetime_minutes" field.
func LifetimeMinutesGT(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldLifetimeMinutes, v))
}

// LifetimeMinutesGTE applies the GTE predicate on the "lifetime_minutes" field.
func LifetimeMinutesGTE(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldLifetimeMinutes, v))
}

// LifetimeMinutesLT applies the LT predicate on the "lifetime_minutes" field.
func LifetimeMinutesLT(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldLifetimeMinutes, v))
}

// LifetimeMinutesLTE applies the LTE predicate on the "lifetime_minutes" field.
func LifetimeMinutesLTE(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldLifetimeMinutes, v))
}

// StrictEQ applies the EQ predicate on the "strict" field.
func StrictEQ(v bool) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldStrict, v))
}

// StrictNEQ applies the NEQ predicate on the "strict" field.
func StrictNEQ(v bool) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldStrict, v))
}

// LastProbeAtEQ applies the EQ predicate on the "last_probe_at" field.
func LastProbeAtEQ(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastProbeAtNEQ applies the NEQ predicate on the "last_probe_at" field.
func LastProbeAtNEQ(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldLastProbeAt, v))
}

// LastProbeAtIn applies the In predicate on the "last_probe_at" field.
func LastProbeAtIn(vs ...time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldLastProbeAt, vs...))
}

// LastProbeAtNotIn applies the NotIn predicate on the "last_probe_at" field.
func LastProbeAtNotIn(vs ...time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldLastProbeAt, vs...))
}

// LastProbeAtGT applies the GT predicate on the "last_probe_at" field.
func LastProbeAtGT(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldLastProbeAt, v))
}

// LastProbeAtGTE applies the GTE predicate on the "last_probe_at" field.
func LastProbeAtGTE(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldLastProbeAt, v))
}

// LastProbeAtLT applies the LT predicate on the "last_probe_at" field.
func LastProbeAtLT(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldLastProbeAt, v))
}

// LastProbeAtLTE applies the LTE predicate on the "last_probe_at" field.
func LastProbeAtLTE(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldLastProbeAt, v))
}

// LastProbeAtIsNil applies the IsNil predicate on the "last_probe_at" field.
func LastProbeAtIsNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIsNull(FieldLastProbeAt))
}

// LastProbeAtNotNil applies the NotNil predicate on the "last_probe_at" field.
func LastProbeAtNotNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotNull(FieldLastProbeAt))
}

// LastProbeLatencyMsEQ applies the EQ predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsEQ(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLastProbeLatencyMs, v))
}

// LastProbeLatencyMsNEQ applies the NEQ predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsNEQ(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldLastProbeLatencyMs, v))
}

// LastProbeLatencyMsIn applies the In predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsIn(vs ...int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldLastProbeLatencyMs, vs...))
}

// LastProbeLatencyMsNotIn applies the NotIn predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsNotIn(vs ...int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldLastProbeLatencyMs, vs...))
}

// LastProbeLatencyMsGT applies the GT predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsGT(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldLastProbeLatencyMs, v))
}

// LastProbeLatencyMsGTE applies the GTE predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsGTE(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldLastProbeLatencyMs, v))
}

// LastProbeLatencyMsLT applies the LT predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsLT(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldLastProbeLatencyMs, v))
}

// LastProbeLatencyMsLTE applies the LTE predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsLTE(v int) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldLastProbeLatencyMs, v))
}

// LastProbeLatencyMsIsNil applies the IsNil predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsIsNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIsNull(FieldLastProbeLatencyMs))
}

// LastProbeLatencyMsNotNil applies the NotNil predicate on the "last_probe_latency_ms" field.
func LastProbeLatencyMsNotNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotNull(FieldLastProbeLatencyMs))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldContainsFold(FieldLastError, v))
}

// LastErrorAtEQ applies the EQ predicate on the "last_error_at" field.
func LastErrorAtEQ(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldEQ(FieldLastErrorAt, v))
}

// LastErrorAtNEQ applies the NEQ predicate on the "last_error_at" field.
func LastErrorAtNEQ(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNEQ(FieldLastErrorAt, v))
}

// LastErrorAtIn applies the In predicate on the "last_error_at" field.
func LastErrorAtIn(vs ...time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIn(FieldLastErrorAt, vs...))
}

// LastErrorAtNotIn applies the NotIn predicate on the "last_error_at" field.
func LastErrorAtNotIn(vs ...time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotIn(FieldLastErrorAt, vs...))
}

// LastErrorAtGT applies the GT predicate on the "last_error_at" field.
func LastErrorAtGT(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGT(FieldLastErrorAt, v))
}

// LastErrorAtGTE applies the GTE predicate on the "last_error_at" field.
func LastErrorAtGTE(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldGTE(FieldLastErrorAt, v))
}

// LastErrorAtLT applies the LT predicate on the "last_error_at" field.
func LastErrorAtLT(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLT(FieldLastErrorAt, v))
}

// LastErrorAtLTE applies the LTE predicate on the "last_error_at" field.
func LastErrorAtLTE(v time.Time) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldLTE(FieldLastErrorAt, v))
}

// LastErrorAtIsNil applies the IsNil predicate on the "last_error_at" field.
func LastErrorAtIsNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldIsNull(FieldLastErrorAt))
}

// LastErrorAtNotNil applies the NotNil predicate on the "last_error_at" field.
func LastErrorAtNotNil() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.FieldNotNull(FieldLastErrorAt))
}

// HasLeases applies the HasEdge predicate on the "leases" edge.
func HasLeases() predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LeasesTable, LeasesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeasesWith applies the HasEdge predicate on the "leases" edge with a given conditions (other predicates).
func HasLeasesWith(preds ...predicate.ManagedProxyLease) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(func(s *sql.Selector) {
		step := newLeasesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CatProxyProviderConfig) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CatProxyProviderConfig) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CatProxyProviderConfig) predicate.CatProxyProviderConfig {
	return predicate.CatProxyProviderConfig(sql.NotPredicates(p))
}
